In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Classificacao/Aulas/Database/heart_tratado.csv', sep=';', encoding='utf-8')

In [3]:
df.head() # dados.head(10) irá aparecer as 10 primeiras linhas

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0

In [4]:
df.shape

(917, 12)

In [5]:
df2 = pd.DataFrame.copy(df)

In [6]:
df['ChestPainType'].unique() # função que descobre os valores distintos da coluna ChestPainType

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [7]:
df2.Sex.replace({'M':0,'F':1}, inplace=True)

In [8]:
df2.ChestPainType.replace({'TA':0,'ATA':1,'NAP':2,'ASY':3}, inplace=True)
df2.RestingECG.replace({'Normal':0,'ST':1,'LVH':2}, inplace=True)
df2.ExerciseAngina.replace({'N':0,'Y':1}, inplace=True)
df2.ST_Slope.replace({'Up':0,'Flat':1,'Down':2}, inplace=True)

In [9]:
df2.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,1,140,289.0,0,0,172,0,0.0,0,0
1,49,1,2,160,180.0,0,0,156,0,1.0,1,1
2,37,0,1,130,283.0,0,1,98,0,0.0,0,0
3,48,1,3,138,214.0,0,0,108,1,1.5,1,1
4,54,0,2,150,195.0,0,0,122,0,0.0,0,0

In [10]:
df2.dtypes

Age                 int64
Sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol       float64
FastingBS           int64
RestingECG          int64
MaxHR               int64
ExerciseAngina      int64
Oldpeak           float64
ST_Slope            int64
HeartDisease        int64
dtype: object

In [11]:
previsores = df2.iloc[:,0:11].values

In [12]:
previsores # variável sem escalonamento

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]])

In [13]:
previsores.shape

(917, 11)

In [14]:
alvo = df2.iloc[:, 11].values

In [15]:
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [16]:
alvo.shape

(917,)

In [17]:
df2.describe()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.00000,917.000000
mean,53.509269,0.210469,2.251908,132.540894,244.635389,0.233370,0.604144,136.789531,0.404580,0.886696,0.63795,0.552890
std,9.437636,0.407864,0.931502,17.999749,53.347125,0.423206,0.806161,25.467129,0.491078,1.066960,0.60727,0.497466
min,28.000000,0.000000,0.000000,80.000000,85.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.00000,0.000000
25%,47.000000,0.000000,2.000000,120.000000,214.000000,0.000000,0.000000,120.000000,0.000000,0.000000,0.00000,0.000000
50%,54.000000,0.000000,3.000000,130.000000,244.635389,0.000000,0.000000,138.000000,0.000000,0.600000,1.00000,1.000000
75%,60.000000,0.000000,3.000000,140.000000,267.000000,0.000000,1.000000,156.000000,1.000000,1.500000,1.00000,1.000000
max,77.000000,1.000000,3.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.00000,1.000000

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
previsores_esc = StandardScaler().fit_transform(previsores) # variável com escalonamento

In [20]:
previsores_esc

array([[-1.43220634, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       [-0.47805725,  1.9368261 , -0.27058012, ..., -0.82431012,
         0.10625149,  0.59651863],
       [-1.75025603, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       ...,
       [ 0.37007527, -0.51630861,  0.80354095, ...,  1.21313565,
         0.29380223,  0.59651863],
       [ 0.37007527,  1.9368261 , -1.34470119, ..., -0.82431012,
        -0.83150225,  0.59651863],
       [-1.64423947, -0.51630861, -0.27058012, ..., -0.82431012,
        -0.83150225, -1.05109458]])

In [21]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

,0,1,2,3,4,5,6,7,8,9,10
0,-1.432206,-0.516309,-1.344701,0.414627,0.832075,-0.551733,-0.749818,1.383339,-0.824310,-0.831502,-1.051095
1,-0.478057,1.936826,-0.270580,1.526360,-1.212261,-0.551733,-0.749818,0.754736,-0.824310,0.106251,0.596519
2,-1.750256,-0.516309,-1.344701,-0.141240,0.719543,-0.551733,0.491306,-1.523953,-0.824310,-0.831502,-1.051095
3,-0.584074,1.936826,0.803541,0.303453,-0.574578,-0.551733,-0.749818,-1.131075,1.213136,0.575128,0.596519
4,0.052026,-0.516309,-0.270580,0.970493,-0.930931,-0.551733,-0.749818,-0.581047,-0.824310,-0.831502,-1.051095
...,...,...,...,...,...,...,...,...,...,...,...
912,-0.902124,-0.516309,-2.418822,-1.252973,0.363191,-0.551733,-0.749818,-0.188170,-0.824310,0.293802,0.596519
913,1.536257,-0.516309,0.803541,0.636973,-0.968441,1.812470,-0.749818,0.165420,-0.824310,2.356860,0.596519
914,0.370075,-0.516309,0.803541,-0.141240,-2.131275,-0.551733,-0.749818,-0.856061,1.213136,0.293802,0.596519
915,0.370075,1.936826,-1.344701,-0.141240,-0.161960,-0.551733,1.732430,1.461915,-0.824310,-0.831502,0.596519
916,-1.644239,-0.516309,-0.270580,0.303453,-1.306038,-0.551733,-0.749818,1.422627,-0.824310,-0.831502,-1.051095

In [22]:
previsoresdf.describe()

,0,1,2,3,4,5,6,7,8,9,10
count,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,917.000000,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02
mean,1.859654e-16,7.748558e-18,1.046055e-16,7.767929e-16,-1.869340e-16,4.649135e-17,0.000000,-5.114048e-16,-1.046055e-16,7.748558e-17,-3.874279e-17
std,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00
min,-2.704405e+00,-5.163086e-01,-2.418822e+00,-2.920572e+00,-2.994023e+00,-5.517333e-01,-0.749818,-3.016886e+00,-8.243101e-01,-3.269662e+00,-1.051095e+00
25%,-6.900904e-01,-5.163086e-01,-2.705801e-01,-6.971063e-01,-5.745784e-01,-5.517333e-01,-0.749818,-6.596226e-01,-8.243101e-01,-8.315022e-01,-1.051095e+00
50%,5.202558e-02,-5.163086e-01,8.035410e-01,-1.412398e-01,0.000000e+00,-5.517333e-01,-0.749818,4.755658e-02,-8.243101e-01,-2.688500e-01,5.965186e-01
75%,6.881250e-01,-5.163086e-01,8.035410e-01,4.146267e-01,4.194568e-01,-5.517333e-01,0.491306,7.547357e-01,1.213136e+00,5.751284e-01,5.965186e-01
max,2.490407e+00,1.936826e+00,8.035410e-01,3.749826e+00,6.721265e+00,1.812470e+00,1.732430,2.561971e+00,1.213136e+00,4.982571e+00,2.244132e+00

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0

In [25]:
previsores2 = df.iloc[:,0:11].values
previsores2

array([[40, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 'M', 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 'F', 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 'M', 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [26]:
previsores2[:,1] = LabelEncoder().fit_transform(previsores[:,1])
previsores2

array([[40, 0, 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 1, 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 0, 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 0, 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 1, 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 0, 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [27]:
previsores2[:,2] = LabelEncoder().fit_transform(previsores[:,2])
previsores2[:,6] = LabelEncoder().fit_transform(previsores[:,6])
previsores2[:,8] = LabelEncoder().fit_transform(previsores[:,8])
previsores2[:,10] = LabelEncoder().fit_transform(previsores[:,10])
previsores2

array([[40, 0, 1, ..., 0, 0.0, 0],
       [49, 1, 2, ..., 0, 1.0, 1],
       [37, 0, 1, ..., 0, 0.0, 0],
       ...,
       [57, 0, 3, ..., 1, 1.2, 1],
       [57, 1, 1, ..., 0, 0.0, 1],
       [38, 0, 2, ..., 0, 0.0, 0]], dtype=object)

In [28]:
previsores2.shape

(917, 11)

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
previsores3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(),[1,2,6,8,10])], remainder='passthrough').fit_transform(previsores2)

In [31]:
previsores3

array([[1.0, 0.0, 0.0, ..., 0, 172, 0.0],
       [0.0, 1.0, 0.0, ..., 0, 156, 1.0],
       [1.0, 0.0, 0.0, ..., 0, 98, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 115, 1.2],
       [0.0, 1.0, 0.0, ..., 0, 174, 0.0],
       [1.0, 0.0, 0.0, ..., 0, 173, 0.0]], dtype=object)

In [32]:
previsores3.shape

(917, 20)

In [33]:
previsores3df = pd.DataFrame(previsores3)
previsores3df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,40,140,289.0,0,172,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,49,160,180.0,0,156,1.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,37,130,283.0,0,98,0.0
3,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,48,138,214.0,0,108,1.5
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,54,150,195.0,0,122,0.0

In [34]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
previsores3_esc = StandardScaler().fit_transform(previsores3)

In [37]:
previsores3_esc

array([[ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.38333943, -0.83150225],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         0.75473573,  0.10625149],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -1.52395266, -0.83150225],
       ...,
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -0.85606123,  0.29380223],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         1.46191489, -0.83150225],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.42262716, -0.83150225]])

In [38]:
previsores3df = pd.DataFrame(previsores3_esc)
previsores3df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.516309,-0.516309,-0.229810,2.073784,-0.531524,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.432206,0.414627,0.832075,-0.551733,1.383339,-0.831502
1,-1.936826,1.936826,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,-0.478057,1.526360,-1.212261,-0.551733,0.754736,0.106251
2,0.516309,-0.516309,-0.229810,2.073784,-0.531524,-1.085425,-1.226974,2.037569,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.750256,-0.141240,0.719543,-0.551733,-1.523953,-0.831502
3,-1.936826,1.936826,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,-1.213136,1.213136,-0.869888,0.998910,-0.271607,-0.584074,0.303453,-0.574578,-0.551733,-1.131075,0.575128
4,0.516309,-0.516309,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,0.052026,0.970493,-0.930931,-0.551733,-0.581047,-0.831502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,0.516309,-0.516309,4.351412,-0.482210,-0.531524,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,-0.902124,-1.252973,0.363191,-0.551733,-0.188170,0.293802
913,0.516309,-0.516309,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,1.536257,0.636973,-0.968441,1.812470,0.165420,2.356860
914,0.516309,-0.516309,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,-1.213136,1.213136,-0.869888,0.998910,-0.271607,0.370075,-0.141240,-2.131275,-0.551733,-0.856061,0.293802
915,-1.936826,1.936826,-0.229810,2.073784,-0.531524,-1.085425,-1.226974,-0.490781,1.969177,0.824310,-0.824310,-0.869888,0.998910,-0.271607,0.370075,-0.141240,-0.161960,-0.551733,1.461915,-0.831502
916,0.516309,-0.516309,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.644239,0.303453,-1.306038,-0.551733,1.422627,-0.831502

In [39]:
previsores3df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,917.000000,9.170000e+02,9.170000e+02,9.170000e+02,917.000000,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02
mean,-1.472226e-16,1.084798e-16,6.973702e-17,-3.874279e-17,3.874279e-17,1.937139e-17,-9.298269e-17,1.549712e-17,0.000000,-4.261707e-17,4.261707e-17,-3.874279e-17,0.000000,8.523413e-17,1.859654e-16,7.884157e-16,3.014189e-15,-1.549712e-17,-5.114048e-16,-1.859654e-16
std,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546,1.000546e+00,1.000546e+00,1.000546e+00,1.000546,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00
min,-1.936826e+00,-5.163086e-01,-2.298105e-01,-4.822104e-01,-5.315237e-01,-1.085425e+00,-1.226974e+00,-4.907810e-01,-0.507826,-1.213136e+00,-8.243101e-01,-8.698879e-01,-1.001091,-2.716072e-01,-2.704405e+00,-2.920572e+00,-2.994023e+00,-5.517333e-01,-3.016886e+00,-3.269662e+00
25%,5.163086e-01,-5.163086e-01,-2.298105e-01,-4.822104e-01,-5.315237e-01,-1.085425e+00,-1.226974e+00,-4.907810e-01,-0.507826,-1.213136e+00,-8.243101e-01,-8.698879e-01,-1.001091,-2.716072e-01,-6.900904e-01,-6.971063e-01,-5.745784e-01,-5.517333e-01,-6.596226e-01,-8.315022e-01
50%,5.163086e-01,-5.163086e-01,-2.298105e-01,-4.822104e-01,-5.315237e-01,9.212982e-01,8.150134e-01,-4.907810e-01,-0.507826,8.243101e-01,-8.243101e-01,-8.698879e-01,0.998910,-2.716072e-01,5.202558e-02,-1.412398e-01,3.198360e-15,-5.517333e-01,4.755658e-02,-2.688500e-01
75%,5.163086e-01,-5.163086e-01,-2.298105e-01,-4.822104e-01,-5.315237e-01,9.212982e-01,8.150134e-01,-4.907810e-01,-0.507826,8.243101e-01,1.213136e+00,1.149573e+00,0.998910,-2.716072e-01,6.881250e-01,4.146267e-01,4.194568e-01,-5.517333e-01,7.547357e-01,5.751284e-01
max,5.163086e-01,1.936826e+00,4.351412e+00,2.073784e+00,1.881384e+00,9.212982e-01,8.150134e-01,2.037569e+00,1.969177,8.243101e-01,1.213136e+00,1.149573e+00,0.998910,3.681787e+00,2.490407e+00,3.749826e+00,6.721265e+00,1.812470e+00,2.561971e+00,4.982571e+00

In [40]:
previsores3df.shape

(917, 20)

# Resumo PRÉ-PROCESSAMENTO

**alvo** = variável que se pretende atingir (tem ou não doença cardíaca) - ***Meu comentário: Resultado que será calculado pelo ML***

**previsores** = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas manualmente, sem escalonar. ***Meu comentário: Foram transformadas as colunas não-numéricas para numéricas (Ex.: Sex)***

**previsores_esc** = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas, escalonada. ***Meu comentário: Transformou todas colunas (aqui todas já estavam como numéricas) de forma que ficassem escalonadas (números próximos de zero)***

**previsores2** = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas pelo labelencoder. ***Meu comentário: Com base na variável previsores foi gerado automaticamente a previsores2***

**previsores3** = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder, sem escalonar. ***Meu comentário: Transformadas as colunas que anteriormente eram "Strings" em onehotencoder (que criou novas colunas conforme a necessidade dos valores das colunas)***

**previsores3_esc** = conjunto de variáveis previsoras transformadas pelo labelencoder e onehotencoder escalonada. ***Meu comentário: Usou a previsores3 para escalonar (ou seja, números perto de zero)***

In [41]:
from sklearn.decomposition import PCA

In [42]:
pca = PCA(n_components=8, svd_solver='arpack')

In [43]:
previsores_pca = pca.fit_transform(previsores2)

In [44]:
previsores_pca

array([[ 4.40103132e+01, -3.61636819e+01,  1.06465542e+01, ...,
         4.58246311e-01, -4.34711000e-01,  3.30819241e-02],
       [-6.39907021e+01, -1.39285156e+01,  3.16853190e+01, ...,
         3.97826364e-02, -6.00330707e-01,  1.86708040e-01],
       [ 3.85382812e+01,  3.38988265e+01, -1.24825819e+01, ...,
         1.23869175e+00,  1.06877939e+00, -3.71988651e-01],
       ...,
       [-1.13347685e+02,  2.34873928e+01, -2.51236375e+00, ...,
        -4.39829566e-01, -5.49662110e-01,  8.29506964e-02],
       [-9.11479572e+00, -3.59101508e+01,  4.82792119e+00, ...,
         4.28090440e-01,  1.25057319e+00,  6.18541396e-01],
       [-7.00123113e+01, -3.56771306e+01,  1.21029800e+01, ...,
        -5.04313122e-01, -3.66470629e-01, -8.22364026e-02]])

In [45]:
previsores_pca.shape

(917, 8)

In [46]:
pca.explained_variance_ratio_

array([7.28440824e-01, 1.71830597e-01, 8.12179278e-02, 1.76786945e-02,
       3.26798570e-04, 1.73094321e-04, 1.52880791e-04, 6.10335429e-05])

In [47]:
pca.explained_variance_ratio_.sum()

0.999881851199779

In [48]:
from sklearn.decomposition import KernelPCA

In [49]:
kpca = KernelPCA(n_components=4, kernel='rbf')

In [50]:
previsores_kernel = kpca.fit_transform(previsores2)

In [51]:
previsores_kernel.shape

(917, 4)

In [52]:
previsores_kernel

array([[-0.00161313, -0.00266007, -0.00186814, -0.00263223],
       [-0.00161382, -0.00266122, -0.00186901, -0.00263352],
       [-0.0016132 , -0.00266017, -0.00186822, -0.00263235],
       ...,
       [-0.00161315, -0.00266009, -0.00186816, -0.00263225],
       [-0.00161325, -0.00266026, -0.00186829, -0.00263245],
       [-0.00161314, -0.00266007, -0.00186814, -0.00263224]])

In [53]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=1)

In [54]:
previsores_lda = lda.fit_transform(previsores2, alvo)

In [55]:
previsores_lda

array([[-1.84039906e+00],
       [-1.02850026e+00],
       [-1.31942421e+00],
       [ 5.44796136e-01],
       [-1.07056148e+00],
       [-1.33498689e+00],
       [-2.65709986e+00],
       [-1.71006712e+00],
       [ 1.05406169e+00],
       [-2.19691693e+00],
       [-2.10336229e+00],
       [ 5.60819162e-01],
       [-1.82642106e+00],
       [ 1.02429254e+00],
       [-2.04219711e+00],
       [-1.21482688e+00],
       [-2.02616486e-01],
       [-2.71291883e+00],
       [ 4.99934678e-01],
       [-4.11374508e-01],
       [-2.98063459e+00],
       [-7.04338045e-01],
       [-2.65710181e+00],
       [ 4.75746736e-01],
       [-1.28657725e+00],
       [-1.62448979e+00],
       [ 1.63352464e+00],
       [-1.39514243e+00],
       [-1.90715060e+00],
       [-1.76263888e+00],
       [ 3.45010914e-01],
       [-1.07924898e+00],
       [ 6.51134898e-01],
       [ 4.33824846e-01],
       [-2.60569643e+00],
       [-1.85455855e+00],
       [ 2.39630035e+00],
       [-2.47176887e+00],
       [-1.92388552e+00],
       [ 3.38017188e-01],
       [-2.27325583e+00],
       [ 8.73426311e-02],
       [-1.87150626e+00],
       [-1.33550917e+00],
       [ 9.96326549e-01],
       [ 9.27922312e-01],
       [-1.09083347e+00],
       [-1.88291142e+00],
       [-3.72803870e-01],
       [-5.03532224e-02],
       [ 1.32452375e+00],
       [ 6.51492054e-01],
       [-8.89697929e-01],
       [-2.52100827e+00],
       [ 2.60070583e-01],
       [-2.63939068e+00],
       [ 9.15634004e-01],
       [-2.35800647e-01],
       [-2.36865345e-01],
       [ 1.52940304e+00],
       [-1.92333679e+00],
       [-2.20061041e+00],
       [-8.19942991e-01],
       [ 1.15672101e+00],
       [-2.52975400e+00],
       [-2.38970352e+00],
       [-1.46583740e+00],
       [-2.14767368e+00],
       [ 2.05770693e+00],
       [-6.78382687e-01],
       [ 2.21683868e-01],
       [-1.68081091e+00],
       [ 6.87619732e-03],
       [-1.39842000e+00],
       [ 1.29959968e+00],
       [-1.13654590e+00],
       [ 6.17375347e-01],
       [-1.79220870e+00],
       [-1.16113335e+00],
       [-1.05185445e-01],
       [-1.27383571e+00],
       [-1.73097883e+00],
       [ 4.67374051e-01],
       [-1.83243179e+00],
       [ 1.81985414e+00],
       [ 1.32183078e+00],
       [ 2.26987983e+00],
       [-4.72591559e-01],
       [-1.22243494e+00],
       [ 1.19721579e+00],
       [-2.63868508e+00],
       [-7.04341843e-01],
       [-2.50755980e+00],
       [ 1.66073913e+00],
       [-2.44407390e+00],
       [ 1.28960138e+00],
       [-1.70378134e+00],
       [-8.71445317e-01],
       [-9.89013879e-01],
       [-1.68375177e+00],
       [ 1.39118009e+00],
       [-5.43690689e-01],
       [ 6.91868604e-02],
       [ 1.89514823e+00],
       [ 1.63755797e-01],
       [-8.79010681e-01],
       [-1.27074346e+00],
       [-1.95076279e+00],
       [-8.82809512e-01],
       [-1.35129372e+00],
       [-1.20076624e+00],
       [ 1.83200531e+00],
       [ 7.50276436e-01],
       [-1.67546895e+00],
       [-1.96027121e+00],
       [ 3.25395309e-02],
       [-6.63393029e-02],
       [ 1.32648317e+00],
       [-3.41933406e+00],
       [-1.68711815e+00],
       [-5.86957215e-01],
       [-1.87957254e+00],
       [-7.91600967e-01],
       [ 7.36479139e-03],
       [-1.67025119e+00],
       [-1.38731127e+00],
       [-3.01512029e+00],
       [-1.61156161e+00],
       [-1.74483914e+00],
       [ 4.81958644e-01],
       [-1.08136521e+00],
       [ 6.52609322e-01],
       [ 1.70993327e+00],
       [ 1.30194693e+00],
       [ 5.99909266e-01],
       [-5.10048655e-01],
       [-2.74908130e+00],
       [-1.41603621e+00],
       [ 9.36159090e-01],
       [ 1.26678742e+00],
       [ 1.84649862e+00],
       [ 1.59826767e+00],
       [ 1.36202046e+00],
       [-8.14004401e-01],
       [-1.27535066e+00],
       [-7.37295388e-01],
       [-1.89101502e+00],
       [-2.69754416e+00],
       [-1.92518241e+00],
       [ 2.44925724e+00],
       [-1.60300826e+00],
       [-1.53884139e+00],
       [-1.71675808e+00],
       [-6.74734189e-01],
       [-1.75946428e+00],
       [ 2.20408473e+00],
       [ 7.45959644e-01],
       [-7.55029769e-01],
       [ 1.53933732e+00],
       [-1.37393694e+00],
       [ 1.81658404e+00],
       [ 1.12596469e+00],
       [-1.81817993e+00],
       [-1.85701276e+00],
       [-2.38767562e+00],
       [-3.71801076e-01],
       [ 1.71880646e+00],
       [-1.46882558e+00],
       [-4.12092029e-01],
       [-1.37239254e+00],
       [-1.94037509e+00],
       [-1.60965932e+00],
       [-1.62161018e+00],
       [-1.51076079e+00],
       [ 1.31517443e+00],
       [ 1.28355792e+00],
       [ 7.05280034e-01],
       [-1.54742081e+00],
       [-1.43375054e+00],
       [-1.16001210e+00],
       [ 1.33197741e+00],
       [-1.72913879e+00],
       [ 1.62972472e+00],
       [ 9.74122683e-01],
       [-2.11394381e+00],
       [ 8.25493572e-01],
       [-1.33399233e+00],
       [ 1.60940333e+00],
       [ 6.26303218e-01],
       [ 1.45746842e+00],
       [-4.53668904e-01],
       [-1.42503675e+00],
       [-1.78840020e+00],
       [-1.07356040e+00],
       [-2.86023744e+00],
       [-2.60464811e+00],
       [ 4.90259320e-01],
       [-1.57625284e+00],
       [ 1.04924267e+00],
       [-1.25581344e+00],
       [-2.19172686e+00],
       [-1.32586770e+00],
       [-1.39993083e+00],
       [-2.67173544e+00],
       [-1.38921941e+00],
       [-8.45325271e-02],
       [-1.90691336e+00],
       [-8.11441763e-01],
       [-2.28149562e+00],
       [ 1.63176631e-01],
       [ 1.05008307e+00],
       [-2.48109062e-01],
       [-1.55853899e-01],
       [-2.10831964e+00],
       [ 1.41307213e+00],
       [-3.12313852e+00],
       [ 7.00709510e-02],
       [-1.19561000e+00],
       [-1.73311569e+00],
       [-1.94671877e+00],
       [ 3.36528340e-01],
       [ 3.57785777e-01],
       [-1.94450110e+00],
       [-1.56014270e+00],
       [-9.11200446e-01],
       [ 1.77750370e-01],
       [-1.26321638e+00],
       [ 9.63009993e-01],
       [-1.84194846e+00],
       [-2.02523169e+00],
       [-8.39209603e-01],
       [-1.38933901e+00],
       [-2.34924070e+00],
       [-8.34941602e-01],
       [-2.21350335e+00],
       [-1.76594087e-01],
       [ 1.61616144e+00],
       [-9.70592911e-01],
       [ 1.73820652e+00],
       [ 1.60403081e+00],
       [-1.53640925e+00],
       [ 1.25264240e+00],
       [ 1.11287229e+00],
       [-2.24780087e+00],
       [ 1.38759438e+00],
       [-1.82514909e+00],
       [ 5.95666405e-01],
       [ 2.75148033e+00],
       [ 1.04304035e+00],
       [ 1.34302841e+00],
       [ 6.25814181e-01],
       [ 7.16087966e-01],
       [ 2.84827251e-01],
       [-1.39983791e+00],
       [ 1.59797331e+00],
       [-1.81019149e+00],
       [-2.13640914e+00],
       [-1.63071474e+00],
       [-1.74196086e+00],
       [-2.34487723e+00],
       [-1.10120115e+00],
       [-2.23008343e+00],
       [ 9.82223872e-01],
       [ 1.62431238e-01],
       [ 4.57367702e-01],
       [-1.70428272e+00],
       [ 1.36409258e+00],
       [-1.90800668e+00],
       [ 1.42311587e+00],
       [-7.45653274e-01],
       [-8.22107998e-01],
       [-2.81970573e+00],
       [ 1.42265135e+00],
       [-1.13203280e+00],
       [-2.54664495e+00],
       [-7.88977270e-01],
       [-1.18090983e-01],
       [ 1.26650749e+00],
       [ 6.70049598e-01],
       [-2.44009739e+00],
       [-1.05976401e+00],
       [ 6.55392160e-01],
       [-1.11705077e+00],
       [-2.34653120e+00],
       [-8.02928668e-01],
       [-1.91187514e+00],
       [-7.88515936e-01],
       [-1.67197987e+00],
       [-2.04940364e+00],
       [-2.17549417e+00],
       [-1.27200875e+00],
       [-2.15968317e+00],
       [-8.84390798e-01],
       [ 1.29387862e+00],
       [-1.38330305e+00],
       [ 1.10026225e+00],
       [ 1.66896143e+00],
       [ 9.21163083e-01],
       [ 1.18065592e+00],
       [ 1.66221951e-01],
       [ 9.68297192e-01],
       [-1.60027749e+00],
       [ 3.34304578e-01],
       [ 2.18471469e+00],
       [ 1.27349221e+00],
       [ 1.69928457e-01],
       [ 7.61599737e-01],
       [ 5.38815039e-01],
       [ 4.74969122e-02],
       [ 1.57107328e+00],
       [-5.25587867e-01],
       [ 2.20312694e-01],
       [-1.51546202e-01],
       [-2.89479590e-01],
       [ 2.06101868e+00],
       [-4.17156437e-01],
       [ 4.00472667e-01],
       [ 1.09336198e+00],
       [ 1.82015341e+00],
       [ 4.03005021e-01],
       [ 6.35871980e-01],
       [ 9.66771337e-01],
       [-6.86842467e-01],
       [ 3.01904113e+00],
       [ 3.95373579e-01],
       [ 2.18529575e+00],
       [-1.25134062e+00],
       [ 9.51092340e-01],
       [ 2.04227740e+00],
       [ 2.79268153e+00],
       [-9.83435777e-02],
       [ 2.13475487e-01],
       [-1.79362379e+00],
       [-2.26301554e-01],
       [-4.18896378e-01],
       [-4.80975508e-01],
       [ 4.47563554e-01],
       [ 5.78625711e-01],
       [ 3.25354173e-01],
       [ 1.20560098e+00],
       [ 2.06796372e+00],
       [ 2.92585315e+00],
       [ 1.32991667e+00],
       [ 1.01160275e+00],
       [ 1.10765707e+00],
       [ 4.08649120e-01],
       [ 4.26419440e-01],
       [ 8.98535159e-01],
       [ 1.56220771e+00],
       [ 1.66853242e+00],
       [ 1.00158654e+00],
       [ 7.80365665e-04],
       [ 1.96258718e+00],
       [ 1.40241393e+00],
       [-2.93662175e-01],
       [-8.55072115e-01],
       [ 1.26678728e+00],
       [-3.54058957e-01],
       [ 4.00183364e-01],
       [-8.49529321e-02],
       [ 1.06231616e+00],
       [ 1.01313000e+00],
       [ 1.54921399e-01],
       [ 1.72792935e-01],
       [ 9.61398159e-02],
       [ 4.89178501e-01],
       [ 1.48475379e+00],
       [ 2.30526978e-01],
       [ 1.41763119e+00],
       [ 1.73094576e+00],
       [ 6.72654620e-01],
       [ 1.58682986e+00],
       [ 4.31017165e-01],
       [ 1.29090462e+00],
       [ 2.12330425e+00],
       [-1.57299297e+00],
       [ 7.74793354e-01],
       [ 1.35542571e+00],
       [ 1.88452190e+00],
       [-1.89339471e-01],
       [ 1.38978921e+00],
       [ 1.07244023e+00],
       [ 1.09096588e+00],
       [-8.02311779e-01],
       [ 9.20000168e-02],
       [ 1.23553383e+00],
       [ 1.14047135e+00],
       [ 1.11994891e+00],
       [ 6.72441527e-01],
       [ 1.12142876e+00],
       [ 8.17128060e-01],
       [ 1.35047479e+00],
       [ 4.86167917e-01],
       [ 1.73674394e+00],
       [ 2.27058875e+00],
       [ 6.98284256e-01],
       [-1.16693197e+00],
       [ 1.91730930e+00],
       [ 9.64857356e-01],
       [ 1.13731643e+00],
       [ 3.64437782e-01],
       [ 6.96875398e-01],
       [ 1.65744717e+00],
       [ 1.96876750e+00],
       [ 1.16817918e+00],
       [ 1.67498983e+00],
       [ 1.88255850e+00],
       [ 1.99989744e+00],
       [ 1.22106051e+00],
       [ 1.30839707e+00],
       [ 1.78315365e+00],
       [ 1.13967504e+00],
       [ 1.99731824e+00],
       [ 4.12143505e-01],
       [ 2.27863457e+00],
       [ 6.16655429e-01],
       [ 1.72987258e+00],
       [-7.27957621e-01],
       [ 2.08851896e+00],
       [ 3.30082007e-01],
       [ 1.65162130e+00],
       [-1.00743273e+00],
       [ 1.91690535e+00],
       [ 8.41541355e-01],
       [ 5.26779457e-01],
       [ 8.97740695e-02],
       [-1.71256610e+00],
       [ 1.29886466e+00],
       [ 1.14706170e+00],
       [ 8.62282634e-01],
       [ 1.68653177e+00],
       [-2.93869112e-01],
       [ 2.67729711e+00],
       [ 1.23817440e+00],
       [ 1.62577714e+00],
       [ 2.18921264e-01],
       [-4.15277652e-01],
       [ 1.53632221e+00],
       [ 7.40595669e-01],
       [-7.87339435e-01],
       [-9.46988657e-01],
       [ 1.24592084e+00],
       [ 1.85128561e+00],
       [ 1.58405757e+00],
       [ 1.04091458e+00],
       [ 8.40375653e-01],
       [ 1.31513445e+00],
       [ 5.60471448e-01],
       [ 2.06467981e+00],
       [ 1.91317216e+00],
       [ 1.30278768e+00],
       [ 1.44622147e+00],
       [ 3.76967064e-01],
       [ 1.84152949e+00],
       [ 3.72320241e-01],
       [ 9.27670212e-01],
       [ 5.82768160e-01],
       [ 1.60437510e+00],
       [-6.10985237e-01],
       [ 2.13882910e+00],
       [ 1.38305961e+00],
       [ 2.21468587e+00],
       [-4.85584774e-01],
       [ 1.84197975e+00],
       [-1.38743531e+00],
       [ 9.87280567e-01],
       [-2.19906148e+00],
       [ 5.02390396e-01],
       [ 1.36342777e-01],
       [ 4.62492407e-01],
       [ 1.58504070e+00],
       [ 1.84762927e+00],
       [ 1.72239196e+00],
       [-1.44859248e+00],
       [ 1.83984149e+00],
       [-6.47872269e-02],
       [ 3.06875566e+00],
       [ 1.97472428e+00],
       [ 1.10837702e+00],
       [ 1.24114448e+00],
       [ 2.08538125e+00],
       [-6.97059472e-01],
       [ 2.36989495e+00],
       [ 1.37019924e+00],
       [ 9.93713992e-01],
       [-1.24103413e+00],
       [ 1.19904181e+00],
       [-1.84776090e+00],
       [ 1.36698988e+00],
       [ 9.55338140e-01],
       [ 1.27075405e+00],
       [-6.60760101e-01],
       [ 9.87088319e-01],
       [ 1.55181368e+00],
       [ 4.45379932e-01],
       [ 2.90893209e+00],
       [ 2.33902371e+00],
       [ 2.01728402e+00],
       [ 1.29017077e+00],
       [ 2.59147334e+00],
       [ 1.41734353e+00],
       [ 1.30169590e+00],
       [-3.91878429e-02],
       [ 3.23645905e+00],
       [ 1.40378291e+00],
       [ 1.73094010e+00],
       [-1.79626888e-01],
       [ 2.05816970e+00],
       [ 3.59059221e-01],
       [-5.87422495e-01],
       [ 2.44039404e+00],
       [-1.54171651e+00],
       [-2.34298259e-01],
       [-5.63788046e-01],
       [ 8.66775216e-01],
       [ 5.35738817e-01],
       [ 1.38844703e+00],
       [ 2.35068159e+00],
       [ 3.96729448e-01],
       [ 4.42252522e-01],
       [ 2.64765776e+00],
       [ 4.86396969e-01],
       [ 1.11033300e+00],
       [-8.75368601e-01],
       [-1.24350642e+00],
       [ 1.62731294e+00],
       [-1.37891309e+00],
       [ 5.87120601e-01],
       [ 1.44887559e+00],
       [ 1.09847601e+00],
       [ 2.24995325e+00],
       [ 1.05624269e+00],
       [ 1.28572295e+00],
       [ 2.26925596e+00],
       [ 1.23815615e+00],
       [ 1.53647723e+00],
       [ 3.43848807e+00],
       [ 2.02003984e+00],
       [-4.75814237e-01],
       [ 7.97722251e-01],
       [ 1.35919695e+00],
       [ 7.13001111e-01],
       [ 2.51380775e+00],
       [-7.25030081e-01],
       [-6.43512720e-01],
       [ 1.99796887e-01],
       [ 1.03237512e+00],
       [-3.73375834e-01],
       [-1.30024550e+00],
       [ 1.16743659e+00],
       [-7.23805177e-01],
       [ 1.09191878e+00],
       [ 8.11101235e-01],
       [-6.69006999e-01],
       [ 6.42881389e-01],
       [ 3.33390732e+00],
       [ 1.51736279e+00],
       [ 8.35871656e-01],
       [ 2.90937485e+00],
       [-1.14949906e+00],
       [-1.67900759e+00],
       [ 1.22763557e+00],
       [ 1.79583560e+00],
       [ 1.83731589e+00],
       [ 1.53033922e+00],
       [ 1.05118478e+00],
       [ 1.16938945e+00],
       [ 2.27003134e+00],
       [ 1.54603319e+00],
       [ 2.30491041e+00],
       [ 1.91880614e+00],
       [ 1.04107654e+00],
       [ 1.19810191e+00],
       [ 2.08781286e+00],
       [ 1.94405287e+00],
       [ 1.50503324e+00],
       [ 1.77095665e+00],
       [ 2.45651561e+00],
       [ 2.29592160e+00],
       [ 1.63861970e+00],
       [-1.55098257e-02],
       [ 2.03431794e+00],
       [-7.98441709e-01],
       [ 2.08054956e+00],
       [ 4.62321380e-01],
       [ 1.34499980e+00],
       [-3.57975706e-01],
       [ 1.44185494e+00],
       [ 9.18074131e-01],
       [-1.56251109e+00],
       [-5.47479775e-01],
       [ 2.99200641e+00],
       [ 1.07190849e+00],
       [ 1.11407849e+00],
       [ 1.59853724e+00],
       [ 5.90964034e-01],
       [-1.16633208e+00],
       [ 2.19328860e+00],
       [ 1.38626938e+00],
       [ 1.36012542e+00],
       [ 9.28068421e-01],
       [ 9.53128103e-01],
       [ 2.57953521e+00],
       [ 2.08041067e-01],
       [-3.10013599e-01],
       [ 2.43057936e+00],
       [ 2.01675425e+00],
       [ 8.93572190e-01],
       [ 3.91164222e-01],
       [ 1.74355315e-01],
       [-2.09066716e+00],
       [ 1.14563769e+00],
       [ 3.51082799e-01],
       [ 4.37963012e-01],
       [ 1.13477095e+00],
       [-2.12652314e-01],
       [-1.51518802e+00],
       [ 1.28483889e+00],
       [-1.31805335e+00],
       [-6.99129337e-01],
       [ 1.24992898e+00],
       [ 1.09928067e+00],
       [ 3.71430113e-01],
       [ 4.42729512e-01],
       [ 1.73386930e-01],
       [ 1.88099403e-01],
       [-1.49304316e+00],
       [-6.71669266e-01],
       [-1.46256932e+00],
       [-2.32796398e-01],
       [ 1.42277259e+00],
       [ 2.85512826e+00],
       [-1.61201739e-01],
       [-1.57913961e+00],
       [ 1.48909912e+00],
       [-9.45302145e-01],
       [ 1.17324166e-01],
       [-8.63799659e-01],
       [-1.06775863e+00],
       [-1.85967488e+00],
       [ 2.61106014e-02],
       [-1.85923554e+00],
       [ 1.42776214e-02],
       [-1.03497351e+00],
       [-2.10971189e-01],
       [-1.69744242e-01],
       [-2.32321636e+00],
       [ 2.67016332e+00],
       [ 1.09589160e+00],
       [ 5.47121143e-01],
       [ 3.26955060e-01],
       [-1.76592983e+00],
       [-1.42343632e+00],
       [-1.11896389e+00],
       [-1.11328519e+00],
       [-1.65686945e+00],
       [-7.97593936e-01],
       [-1.25054824e+00],
       [ 8.30781614e-01],
       [-6.71160621e-01],
       [-1.10461635e+00],
       [-1.14294118e+00],
       [ 2.88209515e-01],
       [-6.83582673e-02],
       [ 1.35776936e+00],
       [-1.35923159e+00],
       [-8.28489510e-01],
       [-2.65589826e+00],
       [-1.63895446e+00],
       [-2.77987178e+00],
       [ 1.56822265e+00],
       [-1.01938426e+00],
       [ 2.26025107e-01],
       [-2.21912560e-02],
       [-8.63727612e-01],
       [ 4.04312210e-01],
       [-1.48906526e+00],
       [-2.81343444e+00],
       [ 8.83997810e-01],
       [ 1.34053552e+00],
       [-3.30490004e-01],
       [-1.59649193e+00],
       [-1.09286637e+00],
       [-1.33169081e+00],
       [ 1.55955254e+00],
       [-6.75270183e-01],
       [-1.43564659e+00],
       [-5.14673357e-01],
       [-1.42016572e+00],
       [ 9.37116291e-01],
       [ 1.19862635e+00],
       [-2.44864741e+00],
       [-1.39137536e+00],
       [-1.76481768e+00],
       [ 8.31403893e-01],
       [ 1.00766386e+00],
       [ 4.48331563e-01],
       [-2.07997207e-01],
       [ 1.16128872e+00],
       [-2.21589108e+00],
       [-9.26042776e-01],
       [ 6.81933460e-01],
       [-2.51930827e+00],
       [ 7.84514921e-01],
       [-1.09744701e+00],
       [-1.45955502e+00],
       [ 1.55216716e+00],
       [ 1.05869586e+00],
       [-8.28017506e-01],
       [ 1.22465629e+00],
       [ 4.01461344e-01],
       [-8.53308034e-01],
       [-1.62099867e+00],
       [-2.38076796e+00],
       [-1.42916163e+00],
       [ 9.67914394e-01],
       [-1.63254691e+00],
       [ 1.35110284e+00],
       [ 5.13848960e-01],
       [ 1.39519064e-01],
       [ 5.16559602e-01],
       [-9.66392241e-02],
       [-2.70020114e-01],
       [-1.65132309e+00],
       [ 1.12983786e+00],
       [-1.83564916e+00],
       [-1.40249226e+00],
       [-1.37137944e+00],
       [-1.77506458e+00],
       [-1.57351304e+00],
       [-6.38870699e-01],
       [ 2.68354766e+00],
       [-2.20455086e-01],
       [ 3.13322744e+00],
       [-2.62913045e-02],
       [ 1.70061885e+00],
       [ 1.59311832e+00],
       [-1.50279206e+00],
       [ 7.71657978e-01],
       [-2.10958372e+00],
       [ 1.58067994e+00],
       [-1.24170143e+00],
       [-1.67966759e+00],
       [ 6.96550735e-01],
       [ 2.87014474e-01],
       [ 6.25506469e-02],
       [-1.09207164e+00],
       [ 2.60746533e+00],
       [-1.02831659e+00],
       [ 5.81453044e-01],
       [-1.96862054e+00],
       [ 1.76047870e+00],
       [-2.84665739e+00],
       [-2.90303694e-01],
       [ 6.87434055e-01],
       [-9.00636205e-01],
       [-3.24645507e-01],
       [-1.07788412e+00],
       [-1.80920989e+00],
       [ 1.61338259e+00],
       [-9.28407983e-01],
       [ 1.18823188e+00],
       [-8.33634300e-01],
       [-1.53358673e+00],
       [-1.55667037e+00],
       [-9.34866837e-01],
       [-2.08410315e+00],
       [ 1.06923690e-01],
       [-1.86700669e+00],

In [56]:
lda.explained_variance_ratio_

array([1.])

In [57]:
import pickle

In [58]:
arq1 = open('heart.pk1', 'wb')

In [59]:
pickle.dump(alvo, arq1)

In [60]:
arq1.close()

In [61]:
arq1 = open('heart.pk1', 'rb')

In [62]:
alvo = pickle.load(arq1)

In [63]:
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

## Treino

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size = 0.3, random_state = 0)

In [66]:
x_treino.shape

(641, 11)

In [67]:
x_teste.shape

(276, 11)

In [68]:
y_treino.shape

(641,)

In [69]:
y_teste.shape

(276,)

## NAIVE BAYES

In [70]:
from sklearn.naive_bayes import GaussianNB

In [71]:
naive = GaussianNB()
naive.fit(x_treino, y_treino)

GaussianNB()

In [72]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0])

In [73]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [74]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [75]:
accuracy_score(y_teste, previsoes_naive)

0.8442028985507246

In [76]:
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_naive) * 100))

Acurácia: 84.42%

In [77]:
confusion_matrix(y_teste, previsoes_naive)

array([[102,  19],
       [ 24, 131]])

In [78]:
print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83       121
           1       0.87      0.85      0.86       155

    accuracy                           0.84       276
   macro avg       0.84      0.84      0.84       276
weighted avg       0.85      0.84      0.84       276

In [79]:
previsoes_treino = naive.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1])

In [80]:
accuracy_score(y_treino, previsoes_treino)

0.8361934477379095

In [81]:
confusion_matrix(y_treino, previsoes_treino)

array([[243,  46],
       [ 59, 293]])

### Validação Cruzada Naive Bayes

In [82]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [83]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [84]:
modelo = GaussianNB()
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

resultado # média dos 30 n_splits é que dá a Acurácia

array([0.83870968, 0.83870968, 0.87096774, 0.87096774, 0.77419355,
       0.80645161, 0.74193548, 0.90322581, 0.80645161, 0.83870968,
       0.90322581, 0.80645161, 0.93548387, 0.80645161, 0.87096774,
       0.90322581, 0.90322581, 0.9       , 0.93333333, 0.8       ,
       0.8       , 0.83333333, 0.76666667, 0.66666667, 0.83333333,
       0.96666667, 0.76666667, 0.86666667, 0.86666667, 0.83333333])

In [85]:

print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 84.18%

## Máquinas de vetores de suporte (SVM)

In [86]:
from sklearn.svm import SVC

In [87]:
svm = SVC(kernel = 'rbf', random_state=1, C = 2)
svm.fit(x_treino, y_treino)

SVC(C=2, random_state=1)

In [88]:
previsoes_svm = svm.predict(x_teste)
previsoes_svm

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0])

In [89]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [90]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [91]:
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_svm) * 100))
# previsores - Acurácia: 85.87%
# previsores_esc - Acurácia: 84.42%
# previsores2 - Acurácia:  85.87%
# previsores3 - Acurácia:  86.23%
# previsores3_esc - Acurácia: 85.87%

Acurácia: 67.03%

In [92]:
confusion_matrix(y_teste, previsoes_svm)

array([[ 68,  53],
       [ 38, 117]])

In [93]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.64      0.56      0.60       121
           1       0.69      0.75      0.72       155

    accuracy                           0.67       276
   macro avg       0.66      0.66      0.66       276
weighted avg       0.67      0.67      0.67       276

In [94]:
previsoes_treino = svm.predict(x_treino)
previsoes_treino

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1])

In [95]:
accuracy_score(y_treino, previsoes_treino)

0.7145085803432137

### Validação Cruzada SVM

In [96]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [97]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [98]:
modelo = SVC(kernel='rbf', random_state=1, C = 2)
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv = kfold)

In [99]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100.0))

Acurácia Média: 85.72%

## Regressão Logística

In [100]:
from sklearn.linear_model import LogisticRegression

In [101]:
logistica = LogisticRegression(random_state=1, max_iter=700, penalty="l2", tol=0.0001, C=1, solver='lbfgs') #lbfgs #newton-cg #sag
logistica.fit(x_treino, y_treino)

LogisticRegression(C=1, max_iter=700, random_state=1)

In [102]:
logistica.intercept_

array([-3.33268446])

In [103]:
logistica.coef_

array([[ 0.0123781 , -1.27430395,  0.66527539,  0.00315881,  0.00427309,
         0.92061278,  0.09485448, -0.01172447,  1.02708424,  0.24925175,
         1.64750739]])

In [104]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [105]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [106]:
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_logistica) * 100))

Acurácia: 85.51%

In [107]:
print(classification_report(y_teste, previsoes_logistica))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       121
           1       0.86      0.88      0.87       155

    accuracy                           0.86       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.86      0.85       276

In [108]:
previsoes_treino = logistica.predict(x_treino)
previsoes_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1])

In [109]:
accuracy_score(y_treino, previsoes_treino)

0.8486739469578783

In [110]:
confusion_matrix(y_treino, previsoes_treino)

array([[238,  51],
       [ 46, 306]])

In [111]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [112]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [113]:
modelo = LogisticRegression(random_state=1, max_iter=700, penalty="l2", tol=0.0001, C=1, solver='lbfgs')
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv = kfold)

In [114]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100.0))

Acurácia Média: 85.83%

## KNN

In [115]:
from sklearn.neighbors import KNeighborsClassifier

In [116]:
knn = KNeighborsClassifier(n_neighbors=37, metric='minkowski', p=1)
knn.fit(x_treino, y_treino)

KNeighborsClassifier(n_neighbors=37, p=1)

In [117]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

In [118]:
y_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1])

In [119]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [120]:
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_knn) * 100))

Acurácia: 71.38%

In [121]:
confusion_matrix(y_teste, previsoes_knn)

array([[ 77,  44],
       [ 35, 120]])

In [122]:
print(classification_report(y_teste, previsoes_knn))

              precision    recall  f1-score   support

           0       0.69      0.64      0.66       121
           1       0.73      0.77      0.75       155

    accuracy                           0.71       276
   macro avg       0.71      0.71      0.71       276
weighted avg       0.71      0.71      0.71       276

In [123]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [124]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [125]:
modelo = KNeighborsClassifier(n_neighbors=37, metric='minkowski', p=1)
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv = kfold)

In [126]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 86.28%

## Árvore de Decisão

In [127]:
from sklearn.tree import DecisionTreeClassifier

In [128]:
arvore = DecisionTreeClassifier(criterion='entropy', random_state=0, max_depth=3)

In [129]:
arvore.fit(x_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [130]:
previsoes_arvore = arvore.predict(x_teste)
previsoes_arvore

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [131]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [132]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [133]:
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_arvore) * 100))

Acurácia: 83.70%

In [134]:
confusion_matrix(y_teste, previsoes_arvore)

array([[105,  16],
       [ 29, 126]])

In [135]:
print(classification_report(y_teste, previsoes_arvore))

              precision    recall  f1-score   support

           0       0.78      0.87      0.82       121
           1       0.89      0.81      0.85       155

    accuracy                           0.84       276
   macro avg       0.84      0.84      0.84       276
weighted avg       0.84      0.84      0.84       276

In [136]:
previsoes_treino = arvore.predict(x_treino)
previsoes_treino

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1])

In [137]:
accuracy_score(y_treino, previsoes_treino)

0.8517940717628705

In [138]:
confusion_matrix(y_treino, previsoes_treino)

array([[249,  40],
       [ 55, 297]])

In [139]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [140]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [141]:
modelo = DecisionTreeClassifier(criterion='entropy', random_state=0, max_depth=3)
resultado = cross_val_score(modelo, previsores3_esc, alvo, cv = kfold)

In [142]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 83.32%

## Random Forest

In [143]:
from sklearn.ensemble import RandomForestClassifier

In [144]:
random = RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state=0, max_depth=4)
random.fit(x_treino, y_treino)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=150,
                       random_state=0)

In [145]:
previsoes_random = random.predict(x_teste)
previsoes_random

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [146]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [147]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_random) * 100))

Acurácia: 86.59%

In [148]:
confusion_matrix(y_teste, previsoes_random)

array([[103,  18],
       [ 19, 136]])

In [149]:
print(classification_report(y_teste, previsoes_random))

              precision    recall  f1-score   support

           0       0.84      0.85      0.85       121
           1       0.88      0.88      0.88       155

    accuracy                           0.87       276
   macro avg       0.86      0.86      0.86       276
weighted avg       0.87      0.87      0.87       276

In [150]:
previsores_treino = random.predict(x_treino)
previsores_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1])

In [151]:
accuracy_score(y_treino, previsores_treino)

0.890795631825273

In [152]:
confusion_matrix(y_treino, previsores_treino)

array([[241,  48],
       [ 22, 330]])

In [153]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [154]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [155]:
modelo =RandomForestClassifier(n_estimators = 150, criterion = 'entropy', random_state=0, max_depth=4)
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

In [156]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 85.92%

## XGBOOST

In [157]:
from xgboost import XGBClassifier

In [158]:
xg = XGBClassifier(max_depth=2, learning_rate=0.05, n_estimators=200, objective='binary:logistic', random_state=3)
xg.fit(x_treino, y_treino)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, random_state=3, ...)

In [159]:
previsores_xg = xg.predict(x_teste)
previsores_xg

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [160]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsores_xg) * 100))

Acurácia: 86.96%

In [161]:
confusion_matrix(y_teste, previsores_xg)

array([[104,  17],
       [ 19, 136]])

In [162]:
print(classification_report(y_teste, previsores_xg))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85       121
           1       0.89      0.88      0.88       155

    accuracy                           0.87       276
   macro avg       0.87      0.87      0.87       276
weighted avg       0.87      0.87      0.87       276

In [163]:
previsores_treino = random.predict(x_treino)
previsores_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1])

In [164]:
accuracy_score(y_treino, previsores_treino)

0.890795631825273

In [165]:
confusion_matrix(y_treino, previsores_treino)

array([[241,  48],
       [ 22, 330]])

In [166]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [167]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [168]:
modelo = XGBClassifier(max_depth=2, learning_rate=0.05, n_estimators=200, objective='binary:logistic', random_state=3)
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

In [169]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 86.81%

## LightGBM

In [170]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.11.4)

In [171]:
import lightgbm as lgb

In [172]:
dataset = lgb.Dataset(x_treino, label=y_treino)

In [173]:
parametros = {'num_leaves':200, # número de folhas
              'objective':'binary', # classificação Binária
              'max_depth':2,
              'learning_rate':.05,
              'max_bin':200
              }

In [174]:
lgbm=lgb.train(parametros,dataset,num_boost_round=150)

[LightGBM] [Info] Number of positive: 352, number of negative: 289
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.135832 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 405
[LightGBM] [Info] Number of data points in the train set: 641, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.549142 -> initscore=0.197204
[LightGBM] [Info] Start training from score 0.197204

In [175]:
from datetime import datetime
inicio=datetime.now()
lbgm=lgb.train(parametros,dataset)
fim=datetime.now()
tempo = fim-inicio
print('Tempo:', tempo)

[LightGBM] [Info] Number of positive: 352, number of negative: 289
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000102 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 405
[LightGBM] [Info] Number of data points in the train set: 641, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.549142 -> initscore=0.197204
[LightGBM] [Info] Start training from score 0.197204
Tempo: 0:00:00.801543

In [176]:
previsoes_lgbm = lgbm.predict(x_teste)
previsoes_lgbm

array([0.89700714, 0.78712887, 0.96558398, 0.03571695, 0.1352966 ,
       0.33090206, 0.4193621 , 0.02565722, 0.06223959, 0.08172317,
       0.89124005, 0.89627415, 0.96580226, 0.94778128, 0.41225337,
       0.90463367, 0.65585867, 0.92517282, 0.90086307, 0.16699149,
       0.89581719, 0.93355958, 0.73933305, 0.2267402 , 0.0437882 ,
       0.023005  , 0.93968732, 0.97080474, 0.60861015, 0.60029817,
       0.94830967, 0.04349684, 0.07461197, 0.06320793, 0.77886196,
       0.09227286, 0.16804848, 0.05606764, 0.66481693, 0.01472752,
       0.02147259, 0.9259166 , 0.92570887, 0.95469378, 0.95105237,
       0.07543263, 0.01170617, 0.90138604, 0.37526725, 0.96644155,
       0.91158002, 0.14234168, 0.11234767, 0.38911407, 0.95993879,
       0.15748908, 0.08890759, 0.14371439, 0.56576202, 0.10449383,
       0.94909427, 0.89878046, 0.59539786, 0.14684041, 0.95714016,
       0.64026269, 0.95885609, 0.31396395, 0.92478554, 0.14684041,
       0.87614664, 0.88398119, 0.32054926, 0.95993879, 0.93158957,
       0.89127993, 0.78290946, 0.9798905 , 0.91006385, 0.82595093,
       0.85431021, 0.87013626, 0.12840333, 0.13070234, 0.86700599,
       0.84487926, 0.86707745, 0.95574022, 0.91464458, 0.19346676,
       0.90257132, 0.32428223, 0.01414853, 0.21849678, 0.64982205,
       0.10499584, 0.88972423, 0.04817248, 0.09174626, 0.14482382,
       0.21347607, 0.74295977, 0.96757105, 0.89832096, 0.14724899,
       0.9262004 , 0.20431228, 0.02292927, 0.16938574, 0.71735235,
       0.47719825, 0.96625757, 0.95517033, 0.92562766, 0.3125173 ,
       0.95493073, 0.4193621 , 0.94450816, 0.9649673 , 0.90328226,
       0.96024746, 0.9877374 , 0.98304808, 0.07315496, 0.60649513,
       0.58102699, 0.19754961, 0.72625754, 0.04417539, 0.95293269,
       0.3118753 , 0.97865144, 0.85877941, 0.79310328, 0.19719548,
       0.48330589, 0.46506398, 0.96365617, 0.78617191, 0.07543263,
       0.26608263, 0.93883776, 0.03661247, 0.91669498, 0.48201914,
       0.04813736, 0.92645475, 0.63953923, 0.52093212, 0.33355859,
       0.41385889, 0.92814932, 0.59745803, 0.07706785, 0.9239754 ,
       0.04012765, 0.83540198, 0.68830916, 0.80062119, 0.01706485,
       0.96535718, 0.61480772, 0.9517722 , 0.4919166 , 0.91158002,
       0.14376424, 0.88226745, 0.01416869, 0.89573894, 0.33112554,
       0.78159915, 0.75214006, 0.03033472, 0.16938574, 0.81435752,
       0.4601921 , 0.62466162, 0.2563091 , 0.18620492, 0.69001723,
       0.95993879, 0.82681096, 0.12351323, 0.95345978, 0.95300907,
       0.9286285 , 0.15531032, 0.88711087, 0.92413726, 0.08384619,
       0.58102604, 0.10238828, 0.9568341 , 0.49643736, 0.91905114,
       0.62860927, 0.24781205, 0.023005  , 0.85617377, 0.05214253,
       0.95994843, 0.8666451 , 0.2321033 , 0.96082705, 0.97943839,
       0.20621601, 0.03580163, 0.0594193 , 0.963065  , 0.25257895,
       0.86803672, 0.97766265, 0.00969777, 0.61593747, 0.11322181,
       0.08263248, 0.92360587, 0.04806513, 0.81146079, 0.74853224,
       0.90847179, 0.1629242 , 0.46777882, 0.59160673, 0.87621496,
       0.92651456, 0.08654255, 0.94697386, 0.29148026, 0.85262888,
       0.02769554, 0.93636603, 0.71527505, 0.93538765, 0.07755872,
       0.87244752, 0.72272147, 0.78616628, 0.0251445 , 0.91220452,
       0.96432311, 0.01170617, 0.91314317, 0.14399482, 0.15699685,
       0.07464601, 0.18813272, 0.26581672, 0.93936535, 0.06777687,
       0.97080474, 0.04970314, 0.8056575 , 0.44418892, 0.01461515,
       0.14868075, 0.97795366, 0.09760706, 0.04573281, 0.92813972,
       0.06307773, 0.50351549, 0.55189352, 0.07860902, 0.53753531,
       0.38848992, 0.01170617, 0.06869262, 0.93572066, 0.0404119 ,
       0.02537121, 0.90974719, 0.94405886, 0.94453833, 0.84406446,
       0.89471843])

In [177]:
previsoes_lgbm.shape

(276,)

In [178]:
for i in range(0,276):
  if previsoes_lgbm[i] >= .5:
    previsoes_lgbm[i] = 1
  else:
    previsoes_lgbm[i] = 0

In [179]:
previsoes_lgbm

array([1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 1., 1.])

In [180]:
y_teste

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [181]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsoes_lgbm) * 100))

Acurácia: 87.32%

In [182]:
confusion_matrix(y_teste, previsoes_lgbm)

array([[104,  17],
       [ 18, 137]])

In [183]:
print(classification_report(y_teste, previsoes_lgbm))

              precision    recall  f1-score   support

           0       0.85      0.86      0.86       121
           1       0.89      0.88      0.89       155

    accuracy                           0.87       276
   macro avg       0.87      0.87      0.87       276
weighted avg       0.87      0.87      0.87       276

In [184]:
previsores_treino = lgbm.predict(x_treino)
previsores_treino

array([0.90641451, 0.46470831, 0.92759429, 0.88103768, 0.78690479,
       0.69101167, 0.12876655, 0.01403481, 0.05765419, 0.05595229,
       0.91754912, 0.03864588, 0.83894386, 0.76907951, 0.9047623 ,
       0.00662736, 0.02537121, 0.16938574, 0.28267062, 0.94778128,
       0.32617577, 0.68906369, 0.90764553, 0.87013626, 0.7629195 ,
       0.10524846, 0.15072764, 0.85246371, 0.61984296, 0.91111878,
       0.96204815, 0.00662736, 0.89120249, 0.96682601, 0.04264519,
       0.245166  , 0.82438857, 0.60921061, 0.03499906, 0.86825327,
       0.09104485, 0.93963284, 0.09041524, 0.08992592, 0.93603569,
       0.96403141, 0.08871876, 0.94217576, 0.95072768, 0.83162481,
       0.49551255, 0.08876264, 0.8069172 , 0.29085103, 0.95000403,
       0.37498969, 0.89089735, 0.03295091, 0.87390736, 0.07464601,
       0.03889723, 0.04791313, 0.58209025, 0.01403481, 0.92946802,
       0.86050244, 0.07147195, 0.57923149, 0.9831437 , 0.00795383,
       0.55301021, 0.92409256, 0.97121593, 0.96774603, 0.0400185 ,
       0.03020859, 0.62866838, 0.95993879, 0.68438133, 0.95869303,
       0.71102486, 0.96015488, 0.96938557, 0.95943852, 0.14766775,
       0.92348333, 0.89974608, 0.55599274, 0.96754042, 0.97118247,
       0.12876655, 0.60260317, 0.07656343, 0.14245609, 0.92145029,
       0.79842736, 0.7629195 , 0.86784947, 0.91959148, 0.95329728,
       0.7095259 , 0.76740663, 0.18313811, 0.620231  , 0.92148142,
       0.92883622, 0.87015678, 0.08612811, 0.49547757, 0.93871661,
       0.01210317, 0.12705613, 0.91968768, 0.1749245 , 0.86011168,
       0.09998496, 0.8207914 , 0.05077755, 0.63080577, 0.25271614,
       0.06462731, 0.03331243, 0.00880832, 0.7866748 , 0.36734807,
       0.9831437 , 0.51144959, 0.0404119 , 0.8794147 , 0.89371287,
       0.92295366, 0.03960241, 0.60216368, 0.78022139, 0.01403481,
       0.36352694, 0.53851092, 0.00795383, 0.92651456, 0.78016736,
       0.03156846, 0.90891173, 0.67011411, 0.93025597, 0.89527803,
       0.90453898, 0.31893597, 0.15999013, 0.37764715, 0.96427436,
       0.95064756, 0.17202227, 0.85863903, 0.03862442, 0.92646841,
       0.00662736, 0.68906369, 0.94405886, 0.75520625, 0.31476609,
       0.9416631 , 0.41225337, 0.04978161, 0.0404119 , 0.62306522,
       0.32514485, 0.88789979, 0.27087008, 0.04978161, 0.06072148,
       0.09648351, 0.88080762, 0.71042771, 0.02623969, 0.93262869,
       0.30130102, 0.08056397, 0.92418054, 0.84810929, 0.01366405,
       0.07001626, 0.03973533, 0.07706785, 0.20336376, 0.04177318,
       0.92562766, 0.94283965, 0.86819178, 0.95887888, 0.82156472,
       0.02623969, 0.27505038, 0.89682791, 0.22699991, 0.07543263,
       0.65620127, 0.809747  , 0.52720886, 0.78037187, 0.91765895,
       0.19615525, 0.30515281, 0.01762593, 0.84230204, 0.71173592,
       0.60815675, 0.69133278, 0.85505496, 0.41381281, 0.14564173,
       0.74467322, 0.18442838, 0.95277224, 0.98151133, 0.85566903,
       0.66481693, 0.86341328, 0.20336376, 0.11673671, 0.93237313,
       0.8201111 , 0.3118753 , 0.17296221, 0.85628891, 0.71676035,
       0.5883165 , 0.93705764, 0.73949386, 0.7353931 , 0.92865358,
       0.88653735, 0.95146298, 0.17872139, 0.96204815, 0.90842981,
       0.0594193 , 0.89682791, 0.06859877, 0.92510292, 0.04148057,
       0.97048466, 0.05456085, 0.80278662, 0.83526632, 0.39538873,
       0.70265672, 0.66579104, 0.90906824, 0.95491252, 0.78641413,
       0.67135165, 0.94189368, 0.00662736, 0.02769554, 0.04177318,
       0.0404119 , 0.0661302 , 0.05294849, 0.24910781, 0.12652377,
       0.48436793, 0.28894783, 0.97865144, 0.51240554, 0.92413726,
       0.2845293 , 0.95943852, 0.43362207, 0.94353937, 0.15340752,
       0.87730267, 0.95074474, 0.11260453, 0.37806236, 0.11079858,
       0.92568301, 0.8514555 , 0.35127701, 0.04761491, 0.08416929,
       0.93140547, 0.20422705, 0.02537121, 0.02537121, 0.7967815 ,
       0.89581719, 0.61366141, 0.83017778, 0.93109436, 0.93820558,
       0.86333482, 0.01461515, 0.95409695, 0.95131074, 0.28572529,
       0.6439159 , 0.07706785, 0.59307439, 0.09856728, 0.96124862,
       0.91910842, 0.08435369, 0.03780795, 0.85752081, 0.03233348,
       0.58920505, 0.57161499, 0.75180707, 0.94217576, 0.08233787,
       0.92413726, 0.03331243, 0.69162844, 0.29041424, 0.96664139,
       0.03052913, 0.86982479, 0.55062242, 0.87351659, 0.2189291 ,
       0.79965973, 0.87635959, 0.94145472, 0.83083365, 0.42506392,
       0.97785833, 0.89309367, 0.84127706, 0.63423164, 0.17843395,
       0.03920424, 0.0671433 , 0.95578706, 0.11722683, 0.00887234,
       0.14245609, 0.83879076, 0.97080474, 0.09377658, 0.75227333,
       0.92425626, 0.85805671, 0.90672954, 0.96340415, 0.9537453 ,
       0.37294184, 0.95090442, 0.88552732, 0.03957157, 0.81879705,
       0.17215174, 0.97811867, 0.08929268, 0.07464601, 0.05416628,
       0.66204899, 0.02565722, 0.66692031, 0.89251332, 0.85813978,
       0.29041424, 0.69502641, 0.20835463, 0.88246093, 0.870956  ,
       0.08946358, 0.02537121, 0.02537121, 0.03033472, 0.01751221,
       0.88011164, 0.67459725, 0.34476279, 0.87484023, 0.2127888 ,
       0.95874703, 0.87981479, 0.93757685, 0.37067058, 0.66200694,
       0.95628805, 0.9184304 , 0.00662736, 0.93855198, 0.09964774,
       0.97191246, 0.19410599, 0.08244654, 0.60762058, 0.91779048,
       0.023005  , 0.47485976, 0.8158158 , 0.66920748, 0.84835283,
       0.92161663, 0.06576944, 0.11537286, 0.32133636, 0.8837984 ,
       0.93103656, 0.98143321, 0.82655331, 0.07001626, 0.95204406,
       0.5659137 , 0.90816568, 0.84983297, 0.54420445, 0.08512492,
       0.35901325, 0.54097217, 0.04847548, 0.85566903, 0.88552732,
       0.84230171, 0.05661604, 0.28912422, 0.18596978, 0.92267508,
       0.92814932, 0.36499488, 0.12494001, 0.90257132, 0.86281928,
       0.37498969, 0.70430564, 0.57265507, 0.03082298, 0.04417539,
       0.0404119 , 0.90166948, 0.9361041 , 0.52206507, 0.93820161,
       0.98043222, 0.95285394, 0.77716197, 0.94145472, 0.8572805 ,
       0.06261153, 0.32829177, 0.92296967, 0.95628805, 0.32192977,
       0.95517033, 0.02868789, 0.92109252, 0.13482135, 0.03784093,
       0.86438374, 0.07464601, 0.86487557, 0.92301965, 0.83514007,
       0.89254001, 0.04177318, 0.0404119 , 0.11828554, 0.94211493,
       0.07464601, 0.93910221, 0.73939883, 0.82785628, 0.83904296,
       0.92304284, 0.9322663 , 0.18285672, 0.92796822, 0.37682491,
       0.82250812, 0.92413726, 0.96292688, 0.91858894, 0.57397592,
       0.94039896, 0.93405766, 0.23382563, 0.0456028 , 0.02565722,
       0.73210845, 0.25553287, 0.14294405, 0.18294766, 0.03795285,
       0.11844327, 0.91910842, 0.07232219, 0.97048466, 0.74734056,
       0.33761407, 0.13015314, 0.10055807, 0.9397981 , 0.84332086,
       0.14909989, 0.53710634, 0.96737023, 0.91039305, 0.0921424 ,
       0.96909461, 0.97563794, 0.02537121, 0.30763294, 0.74940439,
       0.92932179, 0.92000019, 0.83678515, 0.03033472, 0.04680823,
       0.86803672, 0.75897772, 0.59047741, 0.95443795, 0.19719621,
       0.92929968, 0.07787785, 0.09800734, 0.84075217, 0.11270179,
       0.93528562, 0.65416742, 0.8006477 , 0.73267876, 0.04817248,
       0.95674016, 0.89973803, 0.04507816, 0.87484705, 0.16144687,
       0.8753365 , 0.03633717, 0.9446705 , 0.07706785, 0.91464458,
       0.07464601, 0.78784405, 0.06307428, 0.9568341 , 0.70076355,
       0.02997711, 0.92413726, 0.78602281, 0.80747661, 0.90340615,
       0.20401054, 0.20714955, 0.91314317, 0.87852069, 0.11246164,
       0.03136765, 0.59796272, 0.95874703, 0.01170617, 0.91849359,
       0.10437687, 0.85982322, 0.91394494, 0.81465085, 0.28318995,
       0.86090254, 0.94117436, 0.61028947, 0.44710302, 0.03692074,
       0.68486175, 0.96580226, 0.04738853, 0.53753531, 0.96278376,
       0.07706785, 0.90891173, 0.92562766, 0.85405906, 0.06317959,
       0.36221152, 0.95803323, 0.13073249, 0.023005  , 0.51333498,
       0.01375313, 0.53781126, 0.06422837, 0.74599872, 0.96774603,
       0.98074141, 0.71153041, 0.09968104, 0.92967409, 0.10619011,
       0.25343926, 0.27248342, 0.03594513, 0.44331821, 0.12040309,
       0.05860224, 0.80551372, 0.023005  , 0.09768613, 0.56992589,
       0.03122939, 0.11422119, 0.07464601, 0.10537564, 0.9348012 ,
       0.2127888 , 0.51162035, 0.8882127 , 0.43362207, 0.65257094,
       0.93180353, 0.86441993, 0.80772829, 0.94482162, 0.03550288,
       0.83472049, 0.95860906, 0.92831648, 0.27762277, 0.93924639,
       0.91478888, 0.24352796, 0.78302628, 0.62824993, 0.90183895,
       0.9298841 , 0.77462747, 0.86784947, 0.32610299, 0.85888188,
       0.86733241, 0.15699793, 0.03933743, 0.87888776, 0.90807564,
       0.1363026 , 0.94495123, 0.08837533, 0.49305401, 0.04761491,
       0.91885728])

In [185]:
for i in range(0,276):
  if previsoes_treino[i] >= .5:
    previsoes_treino[i] = 1
  else:
    previsoes_treino[i] = 0

In [186]:
previsoes_treino

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1])

In [187]:

accuracy_score(y_treino, previsoes_treino)

0.8517940717628705

In [188]:
confusion_matrix(y_treino, previsoes_treino)

array([[249,  40],
       [ 55, 297]])

In [189]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [190]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [191]:
modelo = lgb.LGBMClassifier(num_leaevs=250, objective='binary', max_depth=2, learning_rate=.05, max_bin=100)
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 397
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000319 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551919 -> initscore=0.208426
[LightGBM] [Info] Start training from score 0.208426
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000165 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553047 -> initscore=0.212991
[LightGBM] [Info] Start training from score 0.212991
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 486, number of negative: 400
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000188 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 340
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.548533 -> initscore=0.194744
[LightGBM] [Info] Start training from score 0.194744
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 487, number of negative: 399
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000262 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.549661 -> initscore=0.199303
[LightGBM] [Info] Start training from score 0.199303
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553047 -> initscore=0.212991
[LightGBM] [Info] Start training from score 0.212991
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000176 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551919 -> initscore=0.208426
[LightGBM] [Info] Start training from score 0.208426
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553047 -> initscore=0.212991
[LightGBM] [Info] Start training from score 0.212991
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 491, number of negative: 395
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000272 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.554176 -> initscore=0.217558
[LightGBM] [Info] Start training from score 0.217558
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 491, number of negative: 395
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000175 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.554176 -> initscore=0.217558
[LightGBM] [Info] Start training from score 0.217558
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000156 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 345
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553047 -> initscore=0.212991
[LightGBM] [Info] Start training from score 0.212991
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 492, number of negative: 394
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000168 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 345
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.555305 -> initscore=0.222128
[LightGBM] [Info] Start training from score 0.222128
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 484, number of negative: 402
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.546275 -> initscore=0.185633
[LightGBM] [Info] Start training from score 0.185633
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551919 -> initscore=0.208426
[LightGBM] [Info] Start training from score 0.208426
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000158 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551919 -> initscore=0.208426
[LightGBM] [Info] Start training from score 0.208426
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 494, number of negative: 392
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000156 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.557562 -> initscore=0.231274
[LightGBM] [Info] Start training from score 0.231274
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 488, number of negative: 398
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000138 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 345
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.550790 -> initscore=0.203863
[LightGBM] [Info] Start training from score 0.203863
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 886, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551919 -> initscore=0.208426
[LightGBM] [Info] Start training from score 0.208426
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 488, number of negative: 399
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000169 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.550169 -> initscore=0.201354
[LightGBM] [Info] Start training from score 0.201354
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000152 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 341
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.552424 -> initscore=0.210469
[LightGBM] [Info] Start training from score 0.210469
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 490, number of negative: 397
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.552424 -> initscore=0.210469
[LightGBM] [Info] Start training from score 0.210469
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 491, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553551 -> initscore=0.215030
[LightGBM] [Info] Start training from score 0.215030
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 491, number of negative: 396
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.553551 -> initscore=0.215030
[LightGBM] [Info] Start training from score 0.215030
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 493, number of negative: 394
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000169 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.555806 -> initscore=0.224158
[LightGBM] [Info] Start training from score 0.224158
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 494, number of negative: 393
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 344
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.556933 -> initscore=0.228726
[LightGBM] [Info] Start training from score 0.228726
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 493, number of negative: 394
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000151 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 341
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.555806 -> initscore=0.224158
[LightGBM] [Info] Start training from score 0.224158
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 487, number of negative: 400
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 343
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.549042 -> initscore=0.196800
[LightGBM] [Info] Start training from score 0.196800
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 489, number of negative: 398
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 341
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.551297 -> initscore=0.205910
[LightGBM] [Info] Start training from score 0.205910
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 492, number of negative: 395
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000154 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 345
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.554679 -> initscore=0.219593
[LightGBM] [Info] Start training from score 0.219593
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Warning] Unknown parameter: num_leaevs
[LightGBM] [Info] Number of positive: 493, number of negative: 394
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 342
[LightGBM] [Info] Number of data points in the train set: 887, number of used features: 11

In [192]:

print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 85.93%

## CATBOOST

In [193]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.2-cp310-cp310-manylinux2014_x86_64.whl (98.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.23.5)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.3.post1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.46.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)
Installing collected packages: catboost
Successfully installed catboost-1.2.2

In [194]:
from catboost import CatBoostClassifier

In [195]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
912,45,M,TA,110,264.0,0,Normal,132,N,1.2,Flat,1
913,68,M,ASY,144,193.0,1,Normal,141,N,3.4,Flat,1
914,57,M,ASY,130,131.0,0,Normal,115,Y,1.2,Flat,1
915,57,F,ATA,130,236.0,0,LVH,174,N,0.0,Flat,1
916,38,M,NAP,138,175.0,0,Normal,173,N,0.0,Up,0

In [196]:
previsores4 = df.iloc[:,0:11]

In [197]:
previsores4.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up

In [198]:
alvo4 = df.iloc[:,11]

In [199]:
from sklearn.model_selection import train_test_split

In [200]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores4, alvo4, test_size=0.3, random_state=0)

In [201]:
categoricas = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

In [202]:
catboost = CatBoostClassifier(task_type='CPU', iterations=120, learning_rate=0.1, depth = 8, random_state = 5, eval_metric='Accuracy')

In [203]:
catboost.fit(x_treino, y_treino, cat_features=categoricas, plot=True, eval_set=(x_teste, y_teste))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.8861154	test: 0.7789855	best: 0.7789855 (0)	total: 57.9ms	remaining: 6.89s
1:	learn: 0.8689548	test: 0.7934783	best: 0.7934783 (1)	total: 67.7ms	remaining: 3.99s
2:	learn: 0.8471139	test: 0.7971014	best: 0.7971014 (2)	total: 71.7ms	remaining: 2.8s
3:	learn: 0.8549142	test: 0.8043478	best: 0.8043478 (3)	total: 77.5ms	remaining: 2.25s
4:	learn: 0.8517941	test: 0.8043478	best: 0.8043478 (3)	total: 86.5ms	remaining: 1.99s
5:	learn: 0.8486739	test: 0.8043478	best: 0.8043478 (3)	total: 98.1ms	remaining: 1.86s
6:	learn: 0.8580343	test: 0.8115942	best: 0.8115942 (6)	total: 111ms	remaining: 1.79s
7:	learn: 0.8642746	test: 0.8043478	best: 0.8115942 (6)	total: 119ms	remaining: 1.67s
8:	learn: 0.8533541	test: 0.8043478	best: 0.8115942 (6)	total: 128ms	remaining: 1.58s
9:	learn: 0.8611544	test: 0.8115942	best: 0.8115942 (6)	total: 139ms	remaining: 1.52s
10:	learn: 0.8642746	test: 0.8079710	best: 0.8115942 (6)	total: 146ms	remaining: 1.45s
11:	learn: 0.8658346	test: 0.8043478	best: 0.8115942 (6)	total: 153ms	remaining: 1.38s
12:	learn: 0.8689548	test: 0.8043478	best: 0.8115942 (6)	total: 161ms	remaining: 1.32s
13:	learn: 0.8611544	test: 0.8007246	best: 0.8115942 (6)	total: 162ms	remaining: 1.23s
14:	learn: 0.8611544	test: 0.8007246	best: 0.8115942 (6)	total: 169ms	remaining: 1.18s
15:	learn: 0.8658346	test: 0.7971014	best: 0.8115942 (6)	total: 176ms	remaining: 1.15s
16:	learn: 0.8673947	test: 0.7971014	best: 0.8115942 (6)	total: 190ms	remaining: 1.15s
17:	learn: 0.8689548	test: 0.8007246	best: 0.8115942 (6)	total: 203ms	remaining: 1.15s
18:	learn: 0.8720749	test: 0.8007246	best: 0.8115942 (6)	total: 222ms	remaining: 1.18s
19:	learn: 0.8767551	test: 0.8007246	best: 0.8115942 (6)	total: 229ms	remaining: 1.14s
20:	learn: 0.8767551	test: 0.8079710	best: 0.8115942 (6)	total: 237ms	remaining: 1.12s
21:	learn: 0.8798752	test: 0.8079710	best: 0.8115942 (6)	total: 247ms	remaining: 1.1s
22:	learn: 0.8814353	test: 0.8079710	best: 0.8115942 (6)	total: 257ms	remaining: 1.08s
23:	learn: 0.8814353	test: 0.8079710	best: 0.8115942 (6)	total: 265ms	remaining: 1.06s
24:	learn: 0.8814353	test: 0.8079710	best: 0.8115942 (6)	total: 275ms	remaining: 1.04s
25:	learn: 0.8829953	test: 0.8115942	best: 0.8115942 (6)	total: 282ms	remaining: 1.02s
26:	learn: 0.8845554	test: 0.8152174	best: 0.8152174 (26)	total: 288ms	remaining: 992ms
27:	learn: 0.8829953	test: 0.8152174	best: 0.8152174 (26)	total: 293ms	remaining: 963ms
28:	learn: 0.8861154	test: 0.8115942	best: 0.8152174 (26)	total: 302ms	remaining: 948ms
29:	learn: 0.8939158	test: 0.8115942	best: 0.8152174 (26)	total: 315ms	remaining: 945ms
30:	learn: 0.8954758	test: 0.8115942	best: 0.8152174 (26)	total: 323ms	remaining: 927ms
31:	learn: 0.8954758	test: 0.8152174	best: 0.8152174 (26)	total: 332ms	remaining: 913ms
32:	learn: 0.8970359	test: 0.8115942	best: 0.8152174 (26)	total: 337ms	remaining: 888ms
33:	learn: 0.9001560	test: 0.8152174	best: 0.8152174 (26)	total: 345ms	remaining: 872ms
34:	learn: 0.9048362	test: 0.8188406	best: 0.8188406 (34)	total: 352ms	remaining: 855ms
35:	learn: 0.9095164	test: 0.8297101	best: 0.8297101 (35)	total: 359ms	remaining: 839ms
36:	learn: 0.9110764	test: 0.8224638	best: 0.8297101 (35)	total: 366ms	remaining: 821ms
37:	learn: 0.9157566	test: 0.8260870	best: 0.8297101 (35)	total: 379ms	remaining: 817ms
38:	learn: 0.9157566	test: 0.8333333	best: 0.8333333 (38)	total: 382ms	remaining: 794ms
39:	learn: 0.9173167	test: 0.8333333	best: 0.8333333 (38)	total: 389ms	remaining: 778ms
40:	learn: 0.9141966	test: 0.8369565	best: 0.8369565 (40)	total: 391ms	remaining: 753ms
41:	learn: 0.9141966	test: 0.8405797	best: 0.8405797 (41)	total: 397ms	remaining: 737ms
42:	learn: 0.9173167	test: 0.8442029	best: 0.8442029 (42)	total: 406ms	remaining: 728ms
43:	learn: 0.9173167	test: 0.8514493	best: 0.8514493 (43)	total: 415ms	remaining: 717ms
44:	learn: 0.9173167	test: 0.8478261	best: 0.8514493 (43)	total: 424ms	remaining: 707ms
45:	learn: 0.9188768	test: 0.8478261	best: 0.8514493 (43)	total: 434ms	remaining: 698ms
46:	learn: 0.9204368	test: 0.8514493	best: 0.8514493 (43)	total: 443ms	remaining: 689ms
47:	learn: 0.9204368	test: 0.8550725	best: 0.8550725 (47)	total: 449ms	remaining: 674ms
48:	learn: 0.9219969	test: 0.8623188	best: 0.8623188 (48)	total: 459ms	remaining: 665ms
49:	learn: 0.9188768	test: 0.8623188	best: 0.8623188 (48)	total: 464ms	remaining: 649ms
50:	learn: 0.9204368	test: 0.8659420	best: 0.8659420 (50)	total: 470ms	remaining: 635ms
51:	learn: 0.9235569	test: 0.8659420	best: 0.8659420 (50)	total: 474ms	remaining: 620ms
52:	learn: 0.9235569	test: 0.8659420	best: 0.8659420 (50)	total: 475ms	remaining: 601ms
53:	learn: 0.9251170	test: 0.8659420	best: 0.8659420 (50)	total: 482ms	remaining: 589ms
54:	learn: 0.9235569	test: 0.8695652	best: 0.8695652 (54)	total: 490ms	remaining: 579ms
55:	learn: 0.9204368	test: 0.8695652	best: 0.8695652 (54)	total: 497ms	remaining: 568ms
56:	learn: 0.9219969	test: 0.8695652	best: 0.8695652 (54)	total: 503ms	remaining: 556ms
57:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 511ms	remaining: 546ms
58:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 526ms	remaining: 543ms
59:	learn: 0.9282371	test: 0.8695652	best: 0.8695652 (54)	total: 536ms	remaining: 536ms
60:	learn: 0.9282371	test: 0.8695652	best: 0.8695652 (54)	total: 543ms	remaining: 525ms
61:	learn: 0.9282371	test: 0.8695652	best: 0.8695652 (54)	total: 546ms	remaining: 511ms
62:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 549ms	remaining: 497ms
63:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 553ms	remaining: 484ms
64:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 554ms	remaining: 469ms
65:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 562ms	remaining: 460ms
66:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 570ms	remaining: 451ms
67:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 573ms	remaining: 438ms
68:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 575ms	remaining: 425ms
69:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 577ms	remaining: 412ms
70:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 580ms	remaining: 401ms
71:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 582ms	remaining: 388ms
72:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 583ms	remaining: 375ms
73:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 591ms	remaining: 367ms
74:	learn: 0.9251170	test: 0.8695652	best: 0.8695652 (54)	total: 592ms	remaining: 355ms
75:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 594ms	remaining: 344ms
76:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 597ms	remaining: 334ms
77:	learn: 0.9266771	test: 0.8695652	best: 0.8695652 (54)	total: 601ms	remaining: 324ms
78:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 604ms	remaining: 314ms
79:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 605ms	remaining: 303ms
80:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 609ms	remaining: 293ms
81:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 611ms	remaining: 283ms
82:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 617ms	remaining: 275ms
83:	learn: 0.9266771	test: 0.8659420	best: 0.8695652 (54)	total: 620ms	remaining: 266ms
84:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 624ms	remaining: 257ms
85:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 632ms	remaining: 250ms
86:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 639ms	remaining: 242ms
87:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 646ms	remaining: 235ms
88:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 652ms	remaining: 227ms
89:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 653ms	remaining: 218ms
90:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 657ms	remaining: 209ms
91:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 661ms	remaining: 201ms
92:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 663ms	remaining: 192ms
93:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 666ms	remaining: 184ms
94:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 668ms	remaining: 176ms
95:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 671ms	remaining: 168ms
96:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 675ms	remaining: 160ms
97:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 680ms	remaining: 153ms
98:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 683ms	remaining: 145ms
99:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 688ms	remaining: 138ms
100:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 692ms	remaining: 130ms
101:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 697ms	remaining: 123ms
102:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 701ms	remaining: 116ms
103:	learn: 0.9282371	test: 0.8623188	best: 0.8695652 (54)	total: 705ms	remaining: 109ms
104:	learn: 0.9282371	test: 0.8623188	best: 0.8695652 (54)	total: 712ms	remaining: 102ms
105:	learn: 0.9282371	test: 0.8623188	best: 0.8695652 (54)	total: 717ms	remaining: 94.7ms
106:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 724ms	remaining: 88ms
107:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 732ms	remaining: 81.3ms
108:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 740ms	remaining: 74.6ms
109:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 743ms	remaining: 67.6ms
110:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 747ms	remaining: 60.6ms
111:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 752ms	remaining: 53.7ms
112:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 758ms	remaining: 46.9ms
113:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 761ms	remaining: 40ms
114:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 765ms	remaining: 33.3ms
115:	learn: 0.9282371	test: 0.8659420	best: 0.8695652 (54)	total: 767ms	remaining: 26.5ms
116:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 771ms	remaining: 19.8ms
117:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 775ms	remaining: 13.1ms
118:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 780ms	remaining: 6.56ms
119:	learn: 0.9297972	test: 0.8659420	best: 0.8695652 (54)	total: 784ms	remaining: 0us

bestTest = 0.8695652174
bestIteration = 54

Shrink model to first 55 iterations.

In [204]:
previsores_cat = catboost.predict(x_teste)
previsores_cat

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [205]:
y_teste

306    1
710    0
298    1
466    0
253    0
      ..
49     1
456    1
342    1
906    1
116    1
Name: HeartDisease, Length: 276, dtype: int64

In [206]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('Acurácia: %.2f%%' % (accuracy_score(y_teste, previsores_cat) * 100))

Acurácia: 86.96%

In [207]:
confusion_matrix(y_teste, previsores_xg)

array([[104,  17],
       [ 19, 136]])

In [208]:
previsores_treino = catboost.predict(x_treino)
previsores_treino

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1])

In [209]:
accuracy_score(y_treino, previsores_treino)

0.9173166926677067

In [210]:
confusion_matrix(y_treino, previsores_treino)

array([[255,  34],
       [ 19, 333]])

In [211]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [212]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [213]:
modelo = CatBoostClassifier(task_type='CPU', iterations=120, learning_rate=0.1, depth = 8, random_state = 5, eval_metric='Accuracy')
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold) # usar previsores para fazer validação cruzada

0:	learn: 0.8803612	total: 7.68ms	remaining: 914ms
1:	learn: 0.8758465	total: 15.2ms	remaining: 900ms
2:	learn: 0.8837472	total: 24.1ms	remaining: 940ms
3:	learn: 0.8927765	total: 30ms	remaining: 870ms
4:	learn: 0.8792325	total: 31.8ms	remaining: 733ms
5:	learn: 0.8803612	total: 39.6ms	remaining: 753ms
6:	learn: 0.8893905	total: 67.8ms	remaining: 1.09s
7:	learn: 0.8860045	total: 79.5ms	remaining: 1.11s
8:	learn: 0.8927765	total: 102ms	remaining: 1.26s
9:	learn: 0.8950339	total: 112ms	remaining: 1.24s
10:	learn: 0.8950339	total: 122ms	remaining: 1.21s
11:	learn: 0.8961625	total: 128ms	remaining: 1.16s
12:	learn: 0.8972912	total: 140ms	remaining: 1.15s
13:	learn: 0.8972912	total: 151ms	remaining: 1.14s
14:	learn: 0.8995485	total: 164ms	remaining: 1.15s
15:	learn: 0.9006772	total: 168ms	remaining: 1.09s
16:	learn: 0.9029345	total: 175ms	remaining: 1.06s
17:	learn: 0.9040632	total: 186ms	remaining: 1.05s
18:	learn: 0.9018059	total: 188ms	remaining: 999ms
19:	learn: 0.9051919	total: 191ms	remaining: 954ms
20:	learn: 0.9029345	total: 202ms	remaining: 952ms
21:	learn: 0.9074492	total: 210ms	remaining: 937ms
22:	learn: 0.9063205	total: 213ms	remaining: 898ms
23:	learn: 0.9085779	total: 216ms	remaining: 864ms
24:	learn: 0.9097065	total: 223ms	remaining: 847ms
25:	learn: 0.9085779	total: 232ms	remaining: 839ms
26:	learn: 0.9097065	total: 244ms	remaining: 839ms
27:	learn: 0.9097065	total: 248ms	remaining: 813ms
28:	learn: 0.9130926	total: 259ms	remaining: 814ms
29:	learn: 0.9119639	total: 266ms	remaining: 797ms
30:	learn: 0.9130926	total: 279ms	remaining: 800ms
31:	learn: 0.9130926	total: 285ms	remaining: 784ms
32:	learn: 0.9130926	total: 297ms	remaining: 783ms
33:	learn: 0.9119639	total: 302ms	remaining: 763ms
34:	learn: 0.9142212	total: 311ms	remaining: 754ms
35:	learn: 0.9142212	total: 326ms	remaining: 760ms
36:	learn: 0.9142212	total: 333ms	remaining: 747ms
37:	learn: 0.9187359	total: 351ms	remaining: 757ms
38:	learn: 0.9164786	total: 360ms	remaining: 747ms
39:	learn: 0.9187359	total: 372ms	remaining: 744ms
40:	learn: 0.9198646	total: 387ms	remaining: 745ms
41:	learn: 0.9209932	total: 394ms	remaining: 732ms
42:	learn: 0.9221219	total: 406ms	remaining: 727ms
43:	learn: 0.9243792	total: 414ms	remaining: 716ms
44:	learn: 0.9232506	total: 424ms	remaining: 707ms
45:	learn: 0.9266366	total: 437ms	remaining: 703ms
46:	learn: 0.9266366	total: 445ms	remaining: 691ms
47:	learn: 0.9277652	total: 452ms	remaining: 677ms
48:	learn: 0.9277652	total: 460ms	remaining: 666ms
49:	learn: 0.9277652	total: 472ms	remaining: 661ms
50:	learn: 0.9266366	total: 480ms	remaining: 650ms
51:	learn: 0.9277652	total: 488ms	remaining: 638ms
52:	learn: 0.9277652	total: 501ms	remaining: 633ms
53:	learn: 0.9277652	total: 524ms	remaining: 640ms
54:	learn: 0.9277652	total: 531ms	remaining: 628ms
55:	learn: 0.9266366	total: 536ms	remaining: 613ms
56:	learn: 0.9277652	total: 542ms	remaining: 599ms
57:	learn: 0.9288939	total: 555ms	remaining: 593ms
58:	learn: 0.9277652	total: 563ms	remaining: 582ms
59:	learn: 0.9277652	total: 575ms	remaining: 575ms
60:	learn: 0.9288939	total: 595ms	remaining: 576ms
61:	learn: 0.9300226	total: 631ms	remaining: 590ms
62:	learn: 0.9300226	total: 639ms	remaining: 578ms
63:	learn: 0.9300226	total: 655ms	remaining: 573ms
64:	learn: 0.9288939	total: 689ms	remaining: 583ms
65:	learn: 0.9300226	total: 699ms	remaining: 572ms
66:	learn: 0.9300226	total: 704ms	remaining: 557ms
67:	learn: 0.9300226	total: 712ms	remaining: 545ms
68:	learn: 0.9300226	total: 719ms	remaining: 531ms
69:	learn: 0.9288939	total: 729ms	remaining: 520ms
70:	learn: 0.9300226	total: 735ms	remaining: 507ms
71:	learn: 0.9300226	total: 738ms	remaining: 492ms
72:	learn: 0.9322799	total: 741ms	remaining: 477ms
73:	learn: 0.9334086	total: 744ms	remaining: 462ms
74:	learn: 0.9334086	total: 746ms	remaining: 448ms
75:	learn: 0.9334086	total: 749ms	remaining: 434ms
76:	learn: 0.9367946	total: 752ms	remaining: 420ms
77:	learn: 0.9367946	total: 754ms	remaining: 406ms
78:	learn: 0.9367946	total: 757ms	remaining: 393ms
79:	learn: 0.9367946	total: 759ms	remaining: 379ms
80:	learn: 0.9356659	total: 763ms	remaining: 367ms
81:	learn: 0.9356659	total: 767ms	remaining: 356ms
82:	learn: 0.9356659	total: 771ms	remaining: 343ms
83:	learn: 0.9356659	total: 774ms	remaining: 332ms
84:	learn: 0.9356659	total: 777ms	remaining: 320ms
85:	learn: 0.9367946	total: 780ms	remaining: 308ms
86:	learn: 0.9367946	total: 785ms	remaining: 298ms
87:	learn: 0.9367946	total: 793ms	remaining: 289ms
88:	learn: 0.9367946	total: 796ms	remaining: 277ms
89:	learn: 0.9367946	total: 803ms	remaining: 268ms
90:	learn: 0.9367946	total: 806ms	remaining: 257ms
91:	learn: 0.9367946	total: 808ms	remaining: 246ms
92:	learn: 0.9367946	total: 816ms	remaining: 237ms
93:	learn: 0.9367946	total: 818ms	remaining: 226ms
94:	learn: 0.9367946	total: 822ms	remaining: 216ms
95:	learn: 0.9367946	total: 834ms	remaining: 208ms
96:	learn: 0.9367946	total: 836ms	remaining: 198ms
97:	learn: 0.9367946	total: 846ms	remaining: 190ms
98:	learn: 0.9367946	total: 849ms	remaining: 180ms
99:	learn: 0.9367946	total: 852ms	remaining: 170ms
100:	learn: 0.9379233	total: 857ms	remaining: 161ms
101:	learn: 0.9379233	total: 865ms	remaining: 153ms
102:	learn: 0.9367946	total: 868ms	remaining: 143ms
103:	learn: 0.9367946	total: 872ms	remaining: 134ms
104:	learn: 0.9367946	total: 877ms	remaining: 125ms
105:	learn: 0.9367946	total: 880ms	remaining: 116ms
106:	learn: 0.9367946	total: 884ms	remaining: 107ms
107:	learn: 0.9379233	total: 896ms	remaining: 99.5ms
108:	learn: 0.9390519	total: 899ms	remaining: 90.8ms
109:	learn: 0.9390519	total: 902ms	remaining: 82ms
110:	learn: 0.9390519	total: 905ms	remaining: 73.4ms
111:	learn: 0.9401806	total: 908ms	remaining: 64.9ms
112:	learn: 0.9390519	total: 911ms	remaining: 56.5ms
113:	learn: 0.9390519	total: 918ms	remaining: 48.3ms
114:	learn: 0.9401806	total: 923ms	remaining: 40.1ms
115:	learn: 0.9401806	total: 932ms	remaining: 32.1ms
116:	learn: 0.9401806	total: 935ms	remaining: 24ms
117:	learn: 0.9390519	total: 938ms	remaining: 15.9ms
118:	learn: 0.9390519	total: 941ms	remaining: 7.91ms
119:	learn: 0.9390519	total: 944ms	remaining: 0us
0:	learn: 0.8735892	total: 18.2ms	remaining: 2.16s
1:	learn: 0.8814898	total: 30.8ms	remaining: 1.82s
2:	learn: 0.8871332	total: 46.3ms	remaining: 1.81s
3:	learn: 0.8871332	total: 56.3ms	remaining: 1.63s
4:	learn: 0.8769752	total: 61.9ms	remaining: 1.42s
5:	learn: 0.8735892	total: 66.6ms	remaining: 1.26s
6:	learn: 0.8758465	total: 70.7ms	remaining: 1.14s
7:	learn: 0.8803612	total: 86.3ms	remaining: 1.21s
8:	learn: 0.8803612	total: 99ms	remaining: 1.22s
9:	learn: 0.8814898	total: 111ms	remaining: 1.22s
10:	learn: 0.8814898	total: 119ms	remaining: 1.18s
11:	learn: 0.8814898	total: 130ms	remaining: 1.17s
12:	learn: 0.8814898	total: 136ms	remaining: 1.12s
13:	learn: 0.8860045	total: 138ms	remaining: 1.05s
14:	learn: 0.8860045	total: 142ms	remaining: 995ms
15:	learn: 0.8882619	total: 149ms	remaining: 966ms
16:	learn: 0.8893905	total: 154ms	remaining: 935ms
17:	learn: 0.8905192	total: 157ms	remaining: 892ms
18:	learn: 0.8927765	total: 163ms	remaining: 865ms
19:	learn: 0.8905192	total: 166ms	remaining: 830ms
20:	learn: 0.8916479	total: 174ms	remaining: 821ms
21:	learn: 0.8927765	total: 179ms	remaining: 796ms
22:	learn: 0.8972912	total: 184ms	remaining: 774ms
23:	learn: 0.8984199	total: 188ms	remaining: 750ms
24:	learn: 0.8984199	total: 197ms	remaining: 747ms
25:	learn: 0.9006772	total: 199ms	remaining: 721ms
26:	learn: 0.9006772	total: 204ms	remaining: 703ms
27:	learn: 0.9051919	total: 208ms	remaining: 684ms
28:	learn: 0.9051919	total: 215ms	remaining: 675ms
29:	learn: 0.9074492	total: 222ms	remaining: 667ms
30:	learn: 0.9074492	total: 231ms	remaining: 664ms
31:	learn: 0.9063205	total: 236ms	remaining: 648ms
32:	learn: 0.9063205	total: 242ms	remaining: 638ms
33:	learn: 0.9063205	total: 246ms	remaining: 622ms
34:	learn: 0.9097065	total: 253ms	remaining: 614ms
35:	learn: 0.9108352	total: 259ms	remaining: 604ms
36:	learn: 0.9108352	total: 268ms	remaining: 601ms
37:	learn: 0.9130926	total: 275ms	remaining: 593ms
38:	learn: 0.9153499	total: 278ms	remaining: 577ms
39:	learn: 0.9164786	total: 283ms	remaining: 565ms
40:	learn: 0.9153499	total: 287ms	remaining: 553ms
41:	learn: 0.9164786	total: 292ms	remaining: 542ms
42:	learn: 0.9164786	total: 297ms	remaining: 532ms
43:	learn: 0.9176072	total: 304ms	remaining: 526ms
44:	learn: 0.9164786	total: 311ms	remaining: 519ms
45:	learn: 0.9176072	total: 318ms	remaining: 511ms
46:	learn: 0.9176072	total: 324ms	remaining: 504ms
47:	learn: 0.9176072	total: 331ms	remaining: 496ms
48:	learn: 0.9198646	total: 333ms	remaining: 483ms
49:	learn: 0.9209932	total: 336ms	remaining: 471ms
50:	learn: 0.9209932	total: 339ms	remaining: 458ms
51:	learn: 0.9209932	total: 348ms	remaining: 456ms
52:	learn: 0.9221219	total: 351ms	remaining: 444ms
53:	learn: 0.9221219	total: 356ms	remaining: 435ms
54:	learn: 0.9255079	total: 359ms	remaining: 424ms
55:	learn: 0.9243792	total: 362ms	remaining: 414ms
56:	learn: 0.9243792	total: 365ms	remaining: 403ms
57:	learn: 0.9255079	total: 368ms	remaining: 393ms
58:	learn: 0.9266366	total: 370ms	remaining: 383ms
59:	learn: 0.9277652	total: 373ms	remaining: 373ms
60:	learn: 0.9277652	total: 378ms	remaining: 365ms
61:	learn: 0.9300226	total: 381ms	remaining: 356ms
62:	learn: 0.9266366	total: 381ms	remaining: 345ms
63:	learn: 0.9277652	total: 384ms	remaining: 336ms
64:	learn: 0.9277652	total: 387ms	remaining: 327ms
65:	learn: 0.9277652	total: 389ms	remaining: 318ms
66:	learn: 0.9277652	total: 392ms	remaining: 310ms
67:	learn: 0.9288939	total: 398ms	remaining: 305ms
68:	learn: 0.9300226	total: 401ms	remaining: 297ms
69:	learn: 0.9311512	total: 409ms	remaining: 292ms
70:	learn: 0.9300226	total: 412ms	remaining: 284ms
71:	learn: 0.9311512	total: 415ms	remaining: 276ms
72:	learn: 0.9311512	total: 417ms	remaining: 269ms
73:	learn: 0.9300226	total: 420ms	remaining: 261ms
74:	learn: 0.9311512	total: 422ms	remaining: 253ms
75:	learn: 0.9300226	total: 425ms	remaining: 246ms
76:	learn: 0.9300226	total: 429ms	remaining: 239ms
77:	learn: 0.9300226	total: 431ms	remaining: 232ms
78:	learn: 0.9300226	total: 435ms	remaining: 226ms
79:	learn: 0.9300226	total: 440ms	remaining: 220ms
80:	learn: 0.9311512	total: 443ms	remaining: 213ms
81:	learn: 0.9300226	total: 445ms	remaining: 206ms
82:	learn: 0.9311512	total: 448ms	remaining: 200ms
83:	learn: 0.9311512	total: 451ms	remaining: 193ms
84:	learn: 0.9311512	total: 453ms	remaining: 187ms
85:	learn: 0.9300226	total: 456ms	remaining: 180ms
86:	learn: 0.9300226	total: 458ms	remaining: 174ms
87:	learn: 0.9300226	total: 460ms	remaining: 167ms
88:	learn: 0.9311512	total: 460ms	remaining: 160ms
89:	learn: 0.9311512	total: 463ms	remaining: 154ms
90:	learn: 0.9288939	total: 465ms	remaining: 148ms
91:	learn: 0.9311512	total: 468ms	remaining: 142ms
92:	learn: 0.9322799	total: 470ms	remaining: 137ms
93:	learn: 0.9322799	total: 474ms	remaining: 131ms
94:	learn: 0.9322799	total: 474ms	remaining: 125ms
95:	learn: 0.9322799	total: 475ms	remaining: 119ms
96:	learn: 0.9322799	total: 476ms	remaining: 113ms
97:	learn: 0.9334086	total: 479ms	remaining: 107ms
98:	learn: 0.9334086	total: 481ms	remaining: 102ms
99:	learn: 0.9345372	total: 484ms	remaining: 96.7ms
100:	learn: 0.9345372	total: 486ms	remaining: 91.4ms
101:	learn: 0.9345372	total: 489ms	remaining: 86.3ms
102:	learn: 0.9345372	total: 491ms	remaining: 81.1ms
103:	learn: 0.9334086	total: 500ms	remaining: 76.9ms
104:	learn: 0.9334086	total: 502ms	remaining: 71.7ms
105:	learn: 0.9334086	total: 504ms	remaining: 66.6ms
106:	learn: 0.9334086	total: 507ms	remaining: 61.6ms
107:	learn: 0.9334086	total: 512ms	remaining: 56.9ms
108:	learn: 0.9334086	total: 520ms	remaining: 52.5ms
109:	learn: 0.9322799	total: 528ms	remaining: 48ms
110:	learn: 0.9334086	total: 532ms	remaining: 43.1ms
111:	learn: 0.9334086	total: 541ms	remaining: 38.6ms
112:	learn: 0.9334086	total: 544ms	remaining: 33.7ms
113:	learn: 0.9322799	total: 547ms	remaining: 28.8ms
114:	learn: 0.9322799	total: 552ms	remaining: 24ms
115:	learn: 0.9334086	total: 559ms	remaining: 19.3ms
116:	learn: 0.9334086	total: 563ms	remaining: 14.4ms
117:	learn: 0.9334086	total: 566ms	remaining: 9.59ms
118:	learn: 0.9345372	total: 569ms	remaining: 4.78ms
119:	learn: 0.9356659	total: 575ms	remaining: 0us
0:	learn: 0.8634312	total: 10.8ms	remaining: 1.28s
1:	learn: 0.8781038	total: 13.4ms	remaining: 788ms
2:	learn: 0.8837472	total: 16.4ms	remaining: 639ms
3:	learn: 0.8871332	total: 24.3ms	remaining: 706ms
4:	learn: 0.8781038	total: 25ms	remaining: 575ms
5:	learn: 0.8826185	total: 33.8ms	remaining: 643ms
6:	learn: 0.8905192	total: 36.4ms	remaining: 587ms
7:	learn: 0.8893905	total: 45.2ms	remaining: 633ms
8:	learn: 0.8961625	total: 54.4ms	remaining: 671ms
9:	learn: 0.8950339	total: 57.4ms	remaining: 631ms
10:	learn: 0.8939052	total: 60.8ms	remaining: 602ms
11:	learn: 0.8939052	total: 73.3ms	remaining: 659ms
12:	learn: 0.8950339	total: 80.8ms	remaining: 665ms
13:	learn: 0.8939052	total: 91.7ms	remaining: 694ms
14:	learn: 0.8961625	total: 100ms	remaining: 703ms
15:	learn: 0.9018059	total: 114ms	remaining: 741ms
16:	learn: 0.9051919	total: 120ms	remaining: 727ms
17:	learn: 0.9029345	total: 134ms	remaining: 759ms
18:	learn: 0.8995485	total: 137ms	remaining: 730ms
19:	learn: 0.9029345	total: 142ms	remaining: 710ms
20:	learn: 0.9040632	total: 155ms	remaining: 732ms
21:	learn: 0.9018059	total: 162ms	remaining: 721ms
22:	learn: 0.9051919	total: 172ms	remaining: 726ms
23:	learn: 0.9074492	total: 181ms	remaining: 724ms
24:	learn: 0.9063205	total: 187ms	remaining: 709ms
25:	learn: 0.9119639	total: 195ms	remaining: 707ms
26:	learn: 0.9108352	total: 206ms	remaining: 708ms
27:	learn: 0.9119639	total: 215ms	remaining: 707ms
28:	learn: 0.9097065	total: 218ms	remaining: 684ms
29:	learn: 0.9130926	total: 231ms	remaining: 693ms
30:	learn: 0.9142212	total: 238ms	remaining: 683ms
31:	learn: 0.9142212	total: 243ms	remaining: 669ms
32:	learn: 0.9164786	total: 256ms	remaining: 674ms
33:	learn: 0.9176072	total: 262ms	remaining: 662ms
34:	learn: 0.9187359	total: 273ms	remaining: 663ms
35:	learn: 0.9187359	total: 281ms	remaining: 656ms
36:	learn: 0.9198646	total: 290ms	remaining: 650ms
37:	learn: 0.9198646	total: 298ms	remaining: 644ms
38:	learn: 0.9198646	total: 307ms	remaining: 638ms
39:	learn: 0.9221219	total: 316ms	remaining: 633ms
40:	learn: 0.9221219	total: 323ms	remaining: 623ms
41:	learn: 0.9232506	total: 336ms	remaining: 625ms
42:	learn: 0.9221219	total: 343ms	remaining: 614ms
43:	learn: 0.9221219	total: 356ms	remaining: 615ms
44:	learn: 0.9221219	total: 369ms	remaining: 616ms
45:	learn: 0.9232506	total: 374ms	remaining: 602ms
46:	learn: 0.9255079	total: 380ms	remaining: 591ms
47:	learn: 0.9232506	total: 386ms	remaining: 580ms
48:	learn: 0.9243792	total: 401ms	remaining: 581ms
49:	learn: 0.9243792	total: 420ms	remaining: 589ms
50:	learn: 0.9243792	total: 427ms	remaining: 577ms
51:	learn: 0.9266366	total: 431ms	remaining: 564ms
52:	learn: 0.9277652	total: 438ms	remaining: 553ms
53:	learn: 0.9288939	total: 445ms	remaining: 544ms
54:	learn: 0.9288939	total: 458ms	remaining: 542ms
55:	learn: 0.9288939	total: 464ms	remaining: 530ms
56:	learn: 0.9288939	total: 475ms	remaining: 525ms
57:	learn: 0.9288939	total: 482ms	remaining: 515ms
58:	learn: 0.9277652	total: 489ms	remaining: 506ms
59:	learn: 0.9288939	total: 503ms	remaining: 503ms
60:	learn: 0.9288939	total: 510ms	remaining: 493ms
61:	learn: 0.9300226	total: 516ms	remaining: 483ms
62:	learn: 0.9300226	total: 522ms	remaining: 472ms
63:	learn: 0.9300226	total: 532ms	remaining: 466ms
64:	learn: 0.9311512	total: 537ms	remaining: 454ms
65:	learn: 0.9322799	total: 549ms	remaining: 449ms
66:	learn: 0.9334086	total: 555ms	remaining: 439ms
67:	learn: 0.9322799	total: 566ms	remaining: 433ms
68:	learn: 0.9322799	total: 576ms	remaining: 426ms
69:	learn: 0.9334086	total: 589ms	remaining: 421ms
70:	learn: 0.9322799	total: 597ms	remaining: 412ms
71:	learn: 0.9334086	total: 605ms	remaining: 403ms
72:	learn: 0.9322799	total: 611ms	remaining: 393ms
73:	learn: 0.9345372	total: 625ms	remaining: 388ms
74:	learn: 0.9356659	total: 640ms	remaining: 384ms
75:	learn: 0.9345372	total: 653ms	remaining: 378ms
76:	learn: 0.9356659	total: 655ms	remaining: 366ms
77:	learn: 0.9367946	total: 659ms	remaining: 355ms
78:	learn: 0.9356659	total: 662ms	remaining: 343ms
79:	learn: 0.9345372	total: 664ms	remaining: 332ms
80:	learn: 0.9379233	total: 667ms	remaining: 321ms
81:	learn: 0.9367946	total: 667ms	remaining: 309ms
82:	learn: 0.9367946	total: 670ms	remaining: 299ms
83:	learn: 0.9390519	total: 673ms	remaining: 288ms
84:	learn: 0.9390519	total: 676ms	remaining: 278ms
85:	learn: 0.9379233	total: 678ms	remaining: 268ms
86:	learn: 0.9379233	total: 681ms	remaining: 258ms
87:	learn: 0.9379233	total: 686ms	remaining: 249ms
88:	learn: 0.9379233	total: 687ms	remaining: 239ms
89:	learn: 0.9379233	total: 691ms	remaining: 230ms
90:	learn: 0.9379233	total: 696ms	remaining: 222ms
91:	learn: 0.9379233	total: 697ms	remaining: 212ms
92:	learn: 0.9379233	total: 701ms	remaining: 204ms
93:	learn: 0.9379233	total: 704ms	remaining: 195ms
94:	learn: 0.9390519	total: 708ms	remaining: 186ms
95:	learn: 0.9401806	total: 715ms	remaining: 179ms
96:	learn: 0.9401806	total: 719ms	remaining: 170ms
97:	learn: 0.9413093	total: 723ms	remaining: 162ms
98:	learn: 0.9424379	total: 726ms	remaining: 154ms
99:	learn: 0.9424379	total: 730ms	remaining: 146ms
100:	learn: 0.9424379	total: 735ms	remaining: 138ms
101:	learn: 0.9424379	total: 739ms	remaining: 130ms
102:	learn: 0.9413093	total: 747ms	remaining: 123ms
103:	learn: 0.9413093	total: 752ms	remaining: 116ms
104:	learn: 0.9413093	total: 754ms	remaining: 108ms
105:	learn: 0.9413093	total: 758ms	remaining: 100ms
106:	learn: 0.9413093	total: 764ms	remaining: 92.9ms
107:	learn: 0.9413093	total: 771ms	remaining: 85.6ms
108:	learn: 0.9413093	total: 778ms	remaining: 78.5ms
109:	learn: 0.9413093	total: 781ms	remaining: 71ms
110:	learn: 0.9424379	total: 785ms	remaining: 63.7ms
111:	learn: 0.9424379	total: 789ms	remaining: 56.3ms
112:	learn: 0.9435666	total: 792ms	remaining: 49.1ms
113:	learn: 0.9435666	total: 795ms	remaining: 41.8ms
114:	learn: 0.9435666	total: 797ms	remaining: 34.6ms
115:	learn: 0.9435666	total: 800ms	remaining: 27.6ms
116:	learn: 0.9435666	total: 803ms	remaining: 20.6ms
117:	learn: 0.9435666	total: 806ms	remaining: 13.7ms
118:	learn: 0.9435666	total: 810ms	remaining: 6.8ms
119:	learn: 0.9435666	total: 813ms	remaining: 0us
0:	learn: 0.8713318	total: 8.13ms	remaining: 968ms
1:	learn: 0.8781038	total: 12.2ms	remaining: 721ms
2:	learn: 0.8950339	total: 20.4ms	remaining: 795ms
3:	learn: 0.8995485	total: 25.8ms	remaining: 747ms
4:	learn: 0.8848758	total: 26.3ms	remaining: 606ms
5:	learn: 0.8826185	total: 27ms	remaining: 513ms
6:	learn: 0.8803612	total: 28.4ms	remaining: 459ms
7:	learn: 0.8792325	total: 34.3ms	remaining: 480ms
8:	learn: 0.8826185	total: 36.7ms	remaining: 452ms
9:	learn: 0.8826185	total: 41.4ms	remaining: 456ms
10:	learn: 0.8871332	total: 47.5ms	remaining: 470ms
11:	learn: 0.8837472	total: 54.5ms	remaining: 490ms
12:	learn: 0.8871332	total: 63.4ms	remaining: 522ms
13:	learn: 0.8860045	total: 67.4ms	remaining: 510ms
14:	learn: 0.8848758	total: 71.2ms	remaining: 499ms
15:	learn: 0.8860045	total: 80.3ms	remaining: 522ms
16:	learn: 0.8837472	total: 86.3ms	remaining: 523ms
17:	learn: 0.8871332	total: 93ms	remaining: 527ms
18:	learn: 0.8893905	total: 99.6ms	remaining: 529ms
19:	learn: 0.8905192	total: 107ms	remaining: 533ms
20:	learn: 0.8916479	total: 112ms	remaining: 530ms
21:	learn: 0.8961625	total: 122ms	remaining: 545ms
22:	learn: 0.8961625	total: 129ms	remaining: 542ms
23:	learn: 0.9018059	total: 131ms	remaining: 525ms
24:	learn: 0.9029345	total: 135ms	remaining: 513ms
25:	learn: 0.9040632	total: 139ms	remaining: 501ms
26:	learn: 0.9051919	total: 142ms	remaining: 490ms
27:	learn: 0.9074492	total: 146ms	remaining: 481ms
28:	learn: 0.9108352	total: 150ms	remaining: 470ms
29:	learn: 0.9108352	total: 153ms	remaining: 458ms

In [214]:
print('Acurácia Média: %.2f%%' % (resultado.mean() * 100))

Acurácia Média: 88.10%

## Salvando dados para Deploy

In [215]:
previsores

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]])

In [216]:
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [217]:
np.savetxt('previsores.csv', previsores, delimiter=',')

In [218]:
np.savetxt('alvo.csv', alvo, delimiter=',')