# IMPORTS

## Preprocessing

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pickle

# PREPROCESSING

In [2]:
df = pd.read_csv('/content/drive/MyDrive/curso_ML/Treinamento/Classificacao/Desafio/Database/cancer_processed.csv', sep=';', encoding='utf-8')

In [3]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_se,concave points_se,radius_worst,texture_worst,perimeter_worst,smoothness_worst,compactness_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,0.9053,0.01587,25.38,17.33,184.60,0.1622,0.6656,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,0.7339,0.01340,24.99,23.41,158.80,0.1238,0.1866,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,0.7869,0.02058,23.57,25.53,152.50,0.1444,0.4245,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,1.1560,0.01867,14.91,26.50,98.87,0.2098,0.8663,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,0.7813,0.01885,22.54,16.67,152.20,0.1374,0.2050,0.1625,0.2364,0.07678

In [4]:
df.shape

(569, 21)

In [5]:
df.dtypes

diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
texture_se                 float64
concave points_se          float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
smoothness_worst           float64
compactness_worst          float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

## Converting nominal categorical variables into ordinal categorical variables

In [6]:
df2 = pd.DataFrame.copy(df)

In [7]:
df2.diagnosis.unique()

array(['M', 'B'], dtype=object)

In [8]:
df2.diagnosis.replace({'M':0, 'B': 1}, inplace=True)

In [9]:
df2.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_se,concave points_se,radius_worst,texture_worst,perimeter_worst,smoothness_worst,compactness_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,0.9053,0.01587,25.38,17.33,184.60,0.1622,0.6656,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,0.7339,0.01340,24.99,23.41,158.80,0.1238,0.1866,0.1860,0.2750,0.08902
2,0,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,0.7869,0.02058,23.57,25.53,152.50,0.1444,0.4245,0.2430,0.3613,0.08758
3,0,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,1.1560,0.01867,14.91,26.50,98.87,0.2098,0.8663,0.2575,0.6638,0.17300
4,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,0.7813,0.01885,22.54,16.67,152.20,0.1374,0.2050,0.1625,0.2364,0.07678

In [10]:
df2.dtypes

diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
texture_se                 float64
concave points_se          float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
smoothness_worst           float64
compactness_worst          float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [11]:
df2.shape

(569, 21)

In [12]:
predictor = df2.iloc[:,1:20].values
predictor

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 6.656e-01, 2.654e-01,
        4.601e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.866e-01, 1.860e-01,
        2.750e-01],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 4.245e-01, 2.430e-01,
        3.613e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 3.094e-01, 1.418e-01,
        2.218e-01],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 8.681e-01, 2.650e-01,
        4.087e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 6.444e-02, 0.000e+00,
        2.871e-01]])

In [395]:
# Generate file to get data to test the simulator

np.savetxt('test_simulator.csv', df2.iloc[:,1:20], delimiter=',')

In [13]:
target = df2.iloc[:, 0].values
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [14]:
target.shape

(569,)

## Analysis of attribute scales (Scaling)

In [15]:
df2.describe()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_se,concave points_se,radius_worst,texture_worst,perimeter_worst,smoothness_worst,compactness_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,0.627417,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,1.216853,0.011796,16.269190,25.677223,107.261213,0.132369,0.254265,0.114606,0.290076,0.083946
std,0.483918,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,0.551648,0.006170,4.833242,6.146258,33.602542,0.022832,0.157336,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,0.360200,0.000000,7.930000,12.020000,50.410000,0.071170,0.027290,0.000000,0.156500,0.055040
25%,0.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,0.833900,0.007638,13.010000,21.080000,84.110000,0.116600,0.147200,0.064930,0.250400,0.071460
50%,1.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,1.108000,0.010930,14.970000,25.410000,97.660000,0.131300,0.211900,0.099930,0.282200,0.080040
75%,1.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,1.474000,0.014710,18.790000,29.720000,125.400000,0.146000,0.339100,0.161400,0.317900,0.092080
max,1.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,4.885000,0.052790,36.040000,49.540000,251.200000,0.222600,1.058000,0.291000,0.663800,0.207500

In [16]:
predictor_scaled = StandardScaler().fit_transform(predictor)
predictor_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.61666502,
         2.29607613,  2.75062224],
       [ 1.82982061, -0.35363241,  1.68595471, ..., -0.43044422,
         1.0870843 , -0.24388967],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.08293217,
         1.95500035,  1.152255  ],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.35073535,
         0.41406869, -1.10454895],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  3.90484795,
         2.28998549,  1.91908301],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.2075525 ,
        -1.74506282, -0.04813821]])

In [17]:
predictor_df_scaled = pd.DataFrame(predictor_scaled)
predictor_df_scaled

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,-0.565265,0.660820,1.886690,-1.359293,2.303601,1.307686,2.616665,2.296076,2.750622
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,-0.876244,0.260162,1.805927,-0.369203,1.535126,-0.375612,-0.430444,1.087084,-0.243890
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,-0.780083,1.424827,1.511870,-0.023974,1.347475,0.527407,1.082932,1.955000,1.152255
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,-0.110409,1.115007,-0.281464,0.133984,-0.249939,3.394275,3.893397,2.175786,6.046041
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,-0.790244,1.144205,1.298575,-1.466770,1.338539,0.220556,-0.313395,0.729259,-0.868353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,0.071025,2.067178,1.901185,0.117700,1.752563,0.378365,-0.273318,1.629151,-1.360158
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,2.260938,0.808431,1.536720,2.047399,1.421940,-0.691230,-0.394820,0.733827,-0.531855
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,-0.257371,0.612157,0.561361,1.374854,0.579001,-0.809587,0.350735,0.414069,-1.104549
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,0.686088,0.785721,1.961239,2.237926,2.303601,1.430427,3.904848,2.289985,1.919083
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,0.383092,-1.913447,-1.410893,0.764190,-1.432735,-1.859019,-1.207552,-1.745063,-0.048138

In [18]:
predictor_df_scaled.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
count,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,569.000000,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02
mean,-1.373633e-16,6.868164e-17,-1.248757e-16,-2.185325e-16,-8.366672e-16,1.873136e-16,4.995028e-17,-4.995028e-17,1.748260e-16,4.745277e-16,-1.123881e-16,0.000000,-8.241796e-16,1.248757e-17,-3.746271e-16,-2.372638e-16,-3.371644e-16,2.247763e-16,2.622390e-16
std,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00
min,-2.029648e+00,-2.229249e+00,-1.984504e+00,-1.454443e+00,-3.112085e+00,-1.610136e+00,-1.114873e+00,-1.261820e+00,-2.744117e+00,-1.819865e+00,-1.554264e+00,-1.913447,-1.726901e+00,-2.223994e+00,-1.693361e+00,-2.682695e+00,-1.443878e+00,-1.745063e+00,-2.160960e+00
25%,-6.893853e-01,-7.259631e-01,-6.919555e-01,-6.671955e-01,-7.109628e-01,-7.470860e-01,-7.437479e-01,-7.379438e-01,-7.032397e-01,-7.226392e-01,-6.948092e-01,-0.674490,-6.749213e-01,-7.486293e-01,-6.895783e-01,-6.912304e-01,-6.810833e-01,-7.563999e-01,-6.418637e-01
50%,-2.150816e-01,-1.046362e-01,-2.359800e-01,-2.951869e-01,-3.489108e-02,-2.219405e-01,-3.422399e-01,-3.977212e-01,-7.162650e-02,-1.782793e-01,-1.974976e-01,-0.140496,-2.690395e-01,-4.351564e-02,-2.859802e-01,-4.684277e-02,-2.695009e-01,-2.234689e-01,-1.274095e-01
75%,4.693926e-01,5.841756e-01,4.996769e-01,3.635073e-01,6.361990e-01,4.938569e-01,5.260619e-01,6.469351e-01,5.307792e-01,4.709834e-01,4.665523e-01,0.472657,5.220158e-01,6.583411e-01,5.402790e-01,5.975448e-01,5.396688e-01,7.125100e-01,4.501382e-01
max,3.971288e+00,4.651889e+00,3.976130e+00,5.250529e+00,4.770911e+00,4.568425e+00,4.243589e+00,3.927930e+00,4.484751e+00,4.910919e+00,6.655279e+00,6.649601,4.094189e+00,3.885905e+00,4.287337e+00,3.955374e+00,5.112877e+00,2.685877e+00,6.046041e+00

## Encoding of categorical variables

### LabelEncoder: transformation of categorical variables into numerical ones

In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_se,concave points_se,radius_worst,texture_worst,perimeter_worst,smoothness_worst,compactness_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,0.9053,0.01587,25.38,17.33,184.60,0.1622,0.6656,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,0.7339,0.01340,24.99,23.41,158.80,0.1238,0.1866,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,0.7869,0.02058,23.57,25.53,152.50,0.1444,0.4245,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,1.1560,0.01867,14.91,26.50,98.87,0.2098,0.8663,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,0.7813,0.01885,22.54,16.67,152.20,0.1374,0.2050,0.1625,0.2364,0.07678

In [20]:
df.shape

(569, 21)

In [21]:
predictor_le = df.iloc[:, 0:21].values
predictor_le

array([['M', 17.99, 10.38, ..., 0.2654, 0.4601, 0.1189],
       ['M', 20.57, 17.77, ..., 0.186, 0.275, 0.08902],
       ['M', 19.69, 21.25, ..., 0.243, 0.3613, 0.08758],
       ...,
       ['M', 16.6, 28.08, ..., 0.1418, 0.2218, 0.0782],
       ['M', 20.6, 29.33, ..., 0.265, 0.4087, 0.124],
       ['B', 7.76, 24.54, ..., 0.0, 0.2871, 0.07039]], dtype=object)

In [22]:
predictor_le[:, 0] = LabelEncoder().fit_transform(predictor_le[:, 0])
predictor_le

array([[1, 17.99, 10.38, ..., 0.2654, 0.4601, 0.1189],
       [1, 20.57, 17.77, ..., 0.186, 0.275, 0.08902],
       [1, 19.69, 21.25, ..., 0.243, 0.3613, 0.08758],
       ...,
       [1, 16.6, 28.08, ..., 0.1418, 0.2218, 0.0782],
       [1, 20.6, 29.33, ..., 0.265, 0.4087, 0.124],
       [0, 7.76, 24.54, ..., 0.0, 0.2871, 0.07039]], dtype=object)

In [23]:
predictor_le.shape

(569, 21)

### OneHotEncoder: Creation of dummy (fictional) variables.

In [24]:
predictor_ohe = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0])],
                                   remainder='passthrough').fit_transform(predictor_le)
predictor_ohe

array([[0.0, 1.0, 17.99, ..., 0.2654, 0.4601, 0.1189],
       [0.0, 1.0, 20.57, ..., 0.186, 0.275, 0.08902],
       [0.0, 1.0, 19.69, ..., 0.243, 0.3613, 0.08758],
       ...,
       [0.0, 1.0, 16.6, ..., 0.1418, 0.2218, 0.0782],
       [0.0, 1.0, 20.6, ..., 0.265, 0.4087, 0.124],
       [1.0, 0.0, 7.76, ..., 0.0, 0.2871, 0.07039]], dtype=object)

In [25]:
predictor_ohe.shape

(569, 22)

In [26]:
predictor_df_ohe = pd.DataFrame(predictor_ohe)
predictor_df_ohe

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,1.0,17.99,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,...,0.9053,0.01587,25.38,17.33,184.6,0.1622,0.6656,0.2654,0.4601,0.1189
1,0.0,1.0,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,0.7339,0.0134,24.99,23.41,158.8,0.1238,0.1866,0.186,0.275,0.08902
2,0.0,1.0,19.69,21.25,130.0,1203.0,0.1096,0.1599,0.1974,0.1279,...,0.7869,0.02058,23.57,25.53,152.5,0.1444,0.4245,0.243,0.3613,0.08758
3,0.0,1.0,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.1052,...,1.156,0.01867,14.91,26.5,98.87,0.2098,0.8663,0.2575,0.6638,0.173
4,0.0,1.0,20.29,14.34,135.1,1297.0,0.1003,0.1328,0.198,0.1043,...,0.7813,0.01885,22.54,16.67,152.2,0.1374,0.205,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,1.0,21.56,22.39,142.0,1479.0,0.111,0.1159,0.2439,0.1389,...,1.256,0.02454,25.45,26.4,166.1,0.141,0.2113,0.2216,0.206,0.07115
565,0.0,1.0,20.13,28.25,131.2,1261.0,0.0978,0.1034,0.144,0.09791,...,2.463,0.01678,23.69,38.25,155.0,0.1166,0.1922,0.1628,0.2572,0.06637
566,0.0,1.0,16.6,28.08,108.3,858.1,0.08455,0.1023,0.09251,0.05302,...,1.075,0.01557,18.98,34.12,126.7,0.1139,0.3094,0.1418,0.2218,0.0782
567,0.0,1.0,20.6,29.33,140.1,1265.0,0.1178,0.277,0.3514,0.152,...,1.595,0.01664,25.74,39.42,184.6,0.165,0.8681,0.265,0.4087,0.124
568,1.0,0.0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.0,0.0,...,1.428,0.0,9.456,30.37,59.16,0.08996,0.06444,0.0,0.2871,0.07039

## Scaling

In [27]:
predictor_ohe_scaled = StandardScaler().fit_transform(predictor_ohe)
predictor_ohe_scaled

array([[-1.29767572,  1.29767572,  1.09706398, ...,  2.29607613,
         2.75062224,  1.93701461],
       [-1.29767572,  1.29767572,  1.82982061, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [-1.29767572,  1.29767572,  1.57988811, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [-1.29767572,  1.29767572,  0.70228425, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [-1.29767572,  1.29767572,  1.83834103, ...,  2.28998549,
         1.91908301,  2.21963528],
       [ 0.77060855, -0.77060855, -1.80840125, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [28]:
predictor_ohe_df_scaled = pd.DataFrame(predictor_ohe_scaled)
predictor_ohe_df_scaled

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,-1.297676,1.297676,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,...,-0.565265,0.660820,1.886690,-1.359293,2.303601,1.307686,2.616665,2.296076,2.750622,1.937015
1,-1.297676,1.297676,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,...,-0.876244,0.260162,1.805927,-0.369203,1.535126,-0.375612,-0.430444,1.087084,-0.243890,0.281190
2,-1.297676,1.297676,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,...,-0.780083,1.424827,1.511870,-0.023974,1.347475,0.527407,1.082932,1.955000,1.152255,0.201391
3,-1.297676,1.297676,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,...,-0.110409,1.115007,-0.281464,0.133984,-0.249939,3.394275,3.893397,2.175786,6.046041,4.935010
4,-1.297676,1.297676,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,...,-0.790244,1.144205,1.298575,-1.466770,1.338539,0.220556,-0.313395,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,-1.297676,1.297676,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,...,0.071025,2.067178,1.901185,0.117700,1.752563,0.378365,-0.273318,1.629151,-1.360158,-0.709091
565,-1.297676,1.297676,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,...,2.260938,0.808431,1.536720,2.047399,1.421940,-0.691230,-0.394820,0.733827,-0.531855,-0.973978
566,-1.297676,1.297676,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,...,-0.257371,0.612157,0.561361,1.374854,0.579001,-0.809587,0.350735,0.414069,-1.104549,-0.318409
567,-1.297676,1.297676,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,...,0.686088,0.785721,1.961239,2.237926,2.303601,1.430427,3.904848,2.289985,1.919083,2.219635
568,0.770609,-0.770609,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,...,0.383092,-1.913447,-1.410893,0.764190,-1.432735,-1.859019,-1.207552,-1.745063,-0.048138,-0.751207

In [29]:
predictor_ohe_df_scaled.describe()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
count,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,...,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02,5.690000e+02
mean,-2.497514e-17,2.497514e-17,-3.153111e-15,-6.568462e-15,-6.993039e-16,-8.553985e-16,6.081447e-15,-1.136369e-15,-2.997017e-16,1.023981e-15,...,-9.084707e-16,-2.684828e-16,-2.297713e-15,1.742016e-15,-1.198807e-15,-5.094929e-15,-2.122887e-15,-1.998011e-16,-2.422589e-15,2.497514e-15
std,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,...,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00,1.000880e+00
min,-1.297676e+00,-7.706085e-01,-2.029648e+00,-2.229249e+00,-1.984504e+00,-1.454443e+00,-3.112085e+00,-1.610136e+00,-1.114873e+00,-1.261820e+00,...,-1.554264e+00,-1.913447e+00,-1.726901e+00,-2.223994e+00,-1.693361e+00,-2.682695e+00,-1.443878e+00,-1.745063e+00,-2.160960e+00,-1.601839e+00
25%,-1.297676e+00,-7.706085e-01,-6.893853e-01,-7.259631e-01,-6.919555e-01,-6.671955e-01,-7.109628e-01,-7.470860e-01,-7.437479e-01,-7.379438e-01,...,-6.948092e-01,-6.744900e-01,-6.749213e-01,-7.486293e-01,-6.895783e-01,-6.912304e-01,-6.810833e-01,-7.563999e-01,-6.418637e-01,-6.919118e-01
50%,7.706085e-01,-7.706085e-01,-2.150816e-01,-1.046362e-01,-2.359800e-01,-2.951869e-01,-3.489108e-02,-2.219405e-01,-3.422399e-01,-3.977212e-01,...,-1.974976e-01,-1.404958e-01,-2.690395e-01,-4.351564e-02,-2.859802e-01,-4.684277e-02,-2.695009e-01,-2.234689e-01,-1.274095e-01,-2.164441e-01
75%,7.706085e-01,1.297676e+00,4.693926e-01,5.841756e-01,4.996769e-01,3.635073e-01,6.361990e-01,4.938569e-01,5.260619e-01,6.469351e-01,...,4.665523e-01,4.726567e-01,5.220158e-01,6.583411e-01,5.402790e-01,5.975448e-01,5.396688e-01,7.125100e-01,4.501382e-01,4.507624e-01
max,7.706085e-01,1.297676e+00,3.971288e+00,4.651889e+00,3.976130e+00,5.250529e+00,4.770911e+00,4.568425e+00,4.243589e+00,3.927930e+00,...,6.655279e+00,6.649601e+00,4.094189e+00,3.885905e+00,4.287337e+00,3.955374e+00,5.112877e+00,2.685877e+00,6.046041e+00,6.846856e+00

## PREPROCESSING SUMMARY

target = Variable to be achieved (whether or not there is heart disease).

predictor = Set of predictor variables with categorical variables manually transformed into numerical ones, without scaling.

predictor_scaled = Set of predictor variables with categorical variables transformed into numerical ones, scaled.

predictor_le = Set of predictor variables with categorical variables transformed into numerical ones using LabelEncoder.

predictor_ohe = Set of predictor variables transformed using LabelEncoder and OneHotEncoder, without scaling.

predictor_ohe_scaled = Set of predictor variables transformed using LabelEncoder and OneHotEncoder, scaled.

## Dimensionality Reduction

The objective is to select the best components (attributes) for algorithm training through the analysis of correlations between variables.

### Principal Component Analysis (PCA)

Feature Selection: Selects the best attributes and uses them without transformations.

Feature Extraction: Identifies relationships among the best attributes and creates new ones.

It is an unsupervised learning algorithm.

Applies to linearly separable data.

In [30]:
pca = PCA(n_components=3)

In [31]:
predictor_pca = pca.fit_transform(predictor_le)

In [32]:
predictor_pca.shape

(569, 3)

In [33]:
predictor_pca

array([[ 353.03276176,  -38.52347996,   28.75885983],
       [ 674.29718155,   12.4130836 ,    2.85194007],
       [ 551.33767605,    5.27130789,    0.85385668],
       ...,
       [ 204.87951797,   -4.79384674,   -9.45568795],
       [ 616.67272382,  -25.32904308,   -4.71798617],
       [-478.22505659,    3.53234742,  -12.29363476]])

In [34]:
pca.explained_variance_ratio_

array([9.98735854e-01, 8.20327786e-04, 3.35625560e-04])

In [35]:
pca.explained_variance_ratio_.sum()

0.999891807302088

### Kernel PCA

It is an unsupervised learning algorithm.

It also applies to linearly non-separable data.

In [36]:
kpca = KernelPCA(n_components=4, kernel='rbf')

In [37]:
predictor_kernel = kpca.fit_transform(predictor_le)

In [38]:
predictor_kernel.shape

(569, 4)

In [39]:
predictor_kernel

array([[-0.00732028, -0.00903089, -0.00128277, -0.00753894],
       [-0.00732476, -0.00903688, -0.00128385, -0.00754546],
       [-0.00742559, -0.00917217, -0.00130838, -0.00769395],
       ...,
       [-0.00732813, -0.00904139, -0.00128466, -0.00755037],
       [-0.00732029, -0.0090309 , -0.00128277, -0.00753896],
       [-0.00935674, -0.01182307, -0.00183033, -0.0108895 ]])

### Linear Discriminant Analysis (LDA)

Supervised Learning Algorithm, as it uses the class as a reference for selection.

Applied in situations with many predictor attributes and also with the target attribute having multiple classes.

In [40]:
lda = LinearDiscriminantAnalysis(n_components = 1)

In [41]:
predictor_lda = lda.fit_transform(predictor_le, target)

In [42]:
predictor_lda

array([[-3.40137745e+00],
       [-2.26018562e+00],
       [-3.83090225e+00],
       [-3.24658800e+00],
       [-1.67059267e+00],
       [-1.44620459e+00],
       [-2.31499698e+00],
       [-9.87087738e-01],
       [-1.72557621e+00],
       [-3.47459370e+00],
       [-7.50392875e-01],
       [-2.28346231e+00],
       [-2.14475398e+00],
       [-3.62754163e-01],
       [-1.35731894e+00],
       [-2.98418650e+00],
       [-1.65212119e+00],
       [-2.93248902e+00],
       [-3.87855365e+00],
       [ 1.07350617e-01],
       [ 1.64019767e+00],
       [ 2.66248452e+00],
       [-1.49080100e+00],
       [-3.53471318e+00],
       [-4.25402149e+00],
       [-3.35265693e+00],
       [-2.49267146e+00],
       [-1.79312020e+00],
       [-2.83057077e+00],
       [-9.04772583e-01],
       [-3.51266716e+00],
       [-1.69263084e+00],
       [-3.70623077e+00],
       [-3.22643277e+00],
       [-2.64649412e+00],
       [-2.42905457e+00],
       [-1.19028222e+00],
       [ 1.32043222e+00],
       [ 9.37114424e-01],
       [-9.07252862e-01],
       [ 4.97221405e-01],
       [-2.22952698e-01],
       [-3.51519651e+00],
       [-1.21161153e+00],
       [-1.27269340e+00],
       [-3.27218064e+00],
       [ 3.08886640e+00],
       [-2.20357988e+00],
       [ 1.23493066e+00],
       [ 3.87036539e-01],
       [ 1.79156776e+00],
       [ 1.47772194e+00],
       [ 1.56172033e+00],
       [-1.58895439e+00],
       [-6.31360480e-01],
       [ 1.06600371e+00],
       [-3.67929599e+00],
       [-1.99634581e+00],
       [ 1.78180223e+00],
       [ 2.22730267e+00],
       [ 2.44225898e+00],
       [ 2.39490767e+00],
       [-1.78259301e+00],
       [ 2.52070415e+00],
       [-2.36844183e+00],
       [-1.92180014e+00],
       [ 1.61601751e+00],
       [ 1.34125525e+00],
       [ 3.45249153e-01],
       [ 1.30111245e+00],
       [-2.11435824e+00],
       [ 3.72431981e+00],
       [-3.62253444e+00],
       [ 3.48451753e-02],
       [ 1.26791105e+00],
       [-1.77793129e+00],
       [ 9.41464141e-01],
       [-2.45513960e+00],
       [-3.76030025e+00],
       [ 1.30707856e+00],
       [ 9.74427967e-01],
       [-7.25519022e-01],
       [-4.54964820e+00],
       [-3.17769179e+00],
       [ 9.79344014e-01],
       [-2.96229138e+00],
       [-5.77878991e-01],
       [-3.47900148e+00],
       [ 1.87191945e-01],
       [-9.42022625e-02],
       [ 6.18525196e-01],
       [-7.41271904e-01],
       [ 1.07051773e+00],
       [ 8.90866353e-01],
       [-1.72647737e+00],
       [-2.70822430e+00],
       [ 1.67079982e+00],
       [ 2.16684928e+00],
       [ 1.15257866e+00],
       [-8.11412094e-01],
       [-4.99634399e-01],
       [ 3.95576591e+00],
       [ 1.17026302e+00],
       [ 1.51723380e+00],
       [ 2.30940896e+00],
       [-2.03084860e+00],
       [ 3.80829148e-01],
       [ 1.54584238e+00],
       [-5.17375053e+00],
       [ 3.23420347e-01],
       [ 2.12976138e+00],
       [ 4.87964667e-01],
       [ 8.79545157e-01],
       [ 2.27722690e+00],
       [ 1.94999219e+00],
       [ 7.44300488e-01],
       [ 3.90125343e+00],
       [-2.37789910e+00],
       [-3.54373793e+00],
       [-1.70462391e+00],
       [ 1.08483508e+00],
       [-2.41261352e+00],
       [-3.96151199e+00],
       [ 6.89256457e-01],
       [ 1.36904381e+00],
       [ 1.61362885e+00],
       [-7.87510541e-01],
       [-1.04020325e+00],
       [ 1.96728739e-01],
       [-2.80244767e+00],
       [ 1.10140899e+00],
       [-1.74783780e+00],
       [-1.02304528e+00],
       [ 4.18897633e-03],
       [-2.20721013e+00],
       [-2.03542274e-02],
       [ 1.36465226e+00],
       [ 1.88016877e+00],
       [-1.66828785e+00],
       [ 1.96082760e+00],
       [ 2.92644164e+00],
       [-8.70982718e-01],
       [ 1.78855930e+00],
       [ 7.83721970e-01],
       [ 2.63014585e+00],
       [ 1.84772689e+00],
       [-9.44304579e-01],
       [ 5.66014681e-01],
       [ 2.19185085e-01],
       [ 1.63545503e+00],
       [ 8.38176820e-01],
       [ 1.11472518e+00],
       [-2.00359616e-01],
       [ 1.93405345e+00],
       [-7.56820634e-02],
       [ 9.97575220e-01],
       [-1.90540660e+00],
       [ 7.42434904e-01],
       [ 1.67099081e+00],
       [ 2.13221102e+00],
       [ 1.02127815e+00],
       [-1.48630641e+00],
       [-4.23406032e+00],
       [ 7.79221928e-01],
       [-3.43012679e+00],
       [ 1.10538660e+00],
       [ 2.54772860e+00],
       [-1.29603707e+00],
       [-2.68794312e+00],
       [ 8.60496171e-01],
       [ 1.15487482e+00],
       [-6.47088337e-01],
       [-1.82985693e+00],
       [ 2.10238206e+00],
       [ 2.80228567e+00],
       [ 3.62893326e+00],
       [ 1.25594116e+00],
       [-1.62116719e+00],
       [ 1.93851936e+00],
       [ 2.05204660e+00],
       [-4.73047135e+00],
       [-4.62544960e+00],
       [-1.90423667e+00],
       [ 2.30431818e+00],
       [-4.35276150e-01],
       [ 1.86031722e+00],
       [-1.08253412e+00],
       [ 1.15683292e+00],
       [ 1.32117980e+00],
       [ 2.17629181e+00],
       [-1.61291648e+00],
       [ 1.31294593e+00],
       [ 2.78308180e+00],
       [-1.77015153e+00],
       [-3.50346836e-01],
       [ 1.15702471e+00],
       [-1.64198697e+00],
       [-3.90718384e-01],
       [-2.12885704e+00],
       [-2.26927094e+00],
       [ 8.25855307e-02],
       [-1.60860158e+00],
       [-4.27567929e+00],
       [-3.69737459e+00],
       [ 2.69134137e-01],
       [-9.72879402e-01],
       [ 2.16726946e+00],
       [-9.11568762e-01],
       [-2.16715044e-01],
       [ 5.33092122e-01],
       [-2.03644038e+00],
       [ 1.52946446e+00],
       [-7.93390609e-01],
       [-8.65595026e-01],
       [-2.51356841e+00],
       [-3.82248334e-01],
       [ 6.93677434e-01],
       [ 2.22372886e+00],
       [-2.94970894e+00],
       [-3.76913358e+00],
       [ 1.32135530e+00],
       [ 9.89283257e-01],
       [ 1.97733370e+00],
       [-2.45415233e+00],
       [ 6.15189408e-01],
       [ 1.69156972e-01],
       [ 2.52969346e+00],
       [ 7.34194863e-01],
       [ 1.00654402e-01],
       [-1.33603032e+00],
       [-2.64644015e+00],
       [ 1.75241049e+00],
       [ 8.72456826e-01],
       [-2.49662437e+00],
       [ 1.51760480e+00],
       [ 8.04358283e-01],
       [-4.51144497e+00],
       [-1.55473871e+00],
       [ 2.38957820e-01],
       [-3.89622544e+00],
       [ 8.26600960e-01],
       [ 1.92659249e+00],
       [ 6.73865749e-01],
       [ 1.01243519e+00],
       [-2.09015328e+00],
       [ 6.47535184e-01],
       [ 1.28716497e+00],
       [ 6.60696626e-01],
       [ 7.38165731e-01],
       [ 1.43095598e+00],
       [-3.55062419e+00],
       [ 1.67014190e+00],
       [-3.94336940e+00],
       [-1.88150315e+00],
       [-3.45278200e+00],
       [-1.23664280e-01],
       [-3.28488755e+00],
       [-2.18313453e+00],
       [-2.06694609e+00],
       [-3.66399471e+00],
       [-3.25929420e+00],
       [-2.52194272e-01],
       [-1.63633107e+00],
       [ 3.48642602e-01],
       [-2.45863353e+00],
       [-4.59949008e+00],
       [ 2.04224593e+00],
       [ 1.34004842e+00],
       [ 1.04790001e+00],
       [ 1.94006349e+00],
       [ 1.93589115e+00],
       [ 1.75547781e+00],
       [-2.77452516e+00],
       [ 1.59211257e+00],
       [-1.41265073e+00],
       [ 8.90295706e-02],
       [ 2.25567957e+00],
       [-8.64676332e-01],
       [ 1.45121759e+00],
       [ 9.46328543e-01],
       [-3.82775046e+00],
       [ 1.12519345e+00],
       [-2.82715415e+00],
       [-1.21577719e+00],
       [ 1.62340162e+00],
       [ 2.13424676e+00],
       [ 8.63029679e-01],
       [ 2.13005176e+00],
       [ 8.20069058e-01],
       [ 1.12684262e+00],
       [ 6.44443485e-01],
       [-2.79038566e-01],
       [ 1.70967024e-01],
       [ 8.35677883e-01],
       [ 2.25014376e+00],
       [ 1.70011823e+00],
       [ 3.07238472e+00],
       [ 1.21204766e+00],
       [ 1.05793041e+00],
       [ 2.35567111e+00],
       [-3.26971501e+00],
       [ 1.51491523e+00],
       [-3.31069255e+00],
       [ 2.02398850e+00],
       [ 2.18856450e+00],
       [ 1.40434172e+00],
       [ 1.81584749e+00],
       [ 3.07479618e+00],
       [ 2.41369057e+00],
       [ 2.09462383e+00],
       [ 1.34702846e+00],
       [ 1.14740054e+00],
       [ 1.41486587e+00],
       [ 2.49419698e+00],
       [ 2.82110336e+00],
       [ 2.40032837e+00],
       [ 2.58739830e+00],
       [-1.99735270e+00],
       [ 2.59535913e+00],
       [ 2.00322306e+00],
       [ 1.50732774e+00],
       [-1.44917697e+00],
       [ 1.07036808e+00],
       [-5.43728080e+00],
       [ 1.62316845e+00],
       [ 1.50739350e+00],
       [ 1.11105451e+00],
       [ 2.29141347e+00],
       [-1.87700961e+00],
       [-1.18507035e+00],
       [-1.27431228e+00],
       [ 7.08787711e-01],
       [ 1.64902508e+00],
       [ 2.24776261e+00],
       [ 1.45375901e+00],
       [-2.63127302e+00],
       [ 2.05688058e+00],
       [-2.94907403e+00],
       [ 1.81142958e+00],
       [-4.68940519e+00],
       [ 1.45610998e-01],
       [ 2.01651798e+00],
       [ 1.29148477e+00],
       [-3.28112562e+00],
       [ 1.14881100e+00],
       [ 2.16393440e+00],
       [ 1.29397886e+00],
       [ 1.63687085e-01],
       [ 9.65420973e-01],
       [ 2.53285073e+00],
       [ 1.79189624e+00],
       [-2.17125844e+00],
       [-5.15328730e+00],
       [-2.42169789e+00],
       [ 2.57194982e+00],
       [ 1.25333573e+00],
       [ 3.21761634e-01],
       [ 1.36328251e+00],
       [ 3.02638607e+00],
       [ 2.06310845e+00],
       [ 2.12107278e+00],
       [ 1.02550221e+00],
       [ 1.37773803e+00],
       [-1.15934534e-01],
       [ 1.13277200e+00],
       [-1.89812395e+00],
       [-3.77863221e+00],
       [ 8.18701187e-01],
       [-2.93563790e+00],
       [-3.42414440e+00],
       [-3.15545906e+00],
       [ 1.26116830e+00],
       [-1.86819630e+00],
       [-2.65141313e+00],
       [ 1.06404455e+00],
       [ 5.67339077e-01],
       [ 1.29669151e+00],
       [ 6.73571326e-01],
       [ 4.07853439e-01],
       [-1.16623532e+00],
       [ 5.77571251e-01],
       [ 2.03312732e+00],
       [ 1.64044595e+00],
       [ 9.05782099e-01],
       [ 1.53064177e+00],
       [-7.97512280e-01],
       [ 1.68518062e+00],
       [ 1.86735023e+00],
       [ 1.99829062e+00],
       [-2.58554349e+00],
       [ 2.42701782e+00],
       [ 2.99127473e+00],
       [-2.92403526e+00],
       [-4.65307115e+00],
       [ 1.10972568e+00],
       [ 8.79172174e-01],
       [ 2.09879951e-01],
       [ 1.55473708e+00],
       [ 1.85272497e+00],
       [ 1.37410983e+00],
       [-2.69783456e+00],
       [ 1.50560244e+00],
       [ 1.45309490e+00],
       [ 1.53823545e+00],
       [ 2.02001301e+00],
       [ 1.38703241e+00],
       [ 4.21815098e-01],
       [ 1.24837574e+00],
       [-2.39337400e+00],
       [ 4.92268945e-01],
       [ 9.48489801e-01],
       [ 1.54496426e+00],
       [ 2.69445703e+00],
       [-2.77285957e-01],
       [-8.59817012e-01],
       [ 9.76525314e-01],
       [ 1.20560802e+00],
       [-2.86595838e+00],
       [ 1.05715497e+00],
       [ 1.58665327e+00],
       [ 1.35043622e+00],
       [ 7.87760431e-01],
       [ 1.46073935e+00],
       [ 4.24224492e-01],
       [ 1.81057563e+00],
       [ 2.25536296e+00],
       [ 1.75617089e+00],
       [ 9.58697472e-01],
       [ 2.31930354e+00],
       [ 1.79272589e+00],
       [-1.33070464e+00],
       [ 1.71322159e+00],
       [-3.21593955e+00],
       [-2.56002025e+00],
       [ 8.30033158e-01],
       [-1.55186464e+00],
       [ 1.13782797e+00],
       [ 6.93562317e-01],
       [ 9.30990188e-01],
       [ 1.50117761e+00],
       [ 1.08329961e+00],
       [-1.99897322e+00],
       [ 2.30301475e+00],
       [ 2.02570596e+00],
       [-5.91969430e-01],
       [ 4.80005396e-01],
       [-2.70405953e+00],
       [ 6.87200667e-01],
       [ 6.00758064e-01],
       [-3.08298667e+00],
       [ 1.48734661e+00],
       [-2.28290262e+00],
       [ 6.35624220e-01],
       [ 1.27669677e-01],
       [ 7.23913437e-01],
       [ 7.86672564e-02],
       [ 4.00059494e-01],
       [ 5.94151884e-01],
       [ 8.72304607e-01],
       [ 1.80803439e+00],
       [-2.88929396e+00],
       [-4.26134821e+00],
       [ 7.67606111e-01],
       [ 1.00238517e+00],
       [ 6.75994413e-01],
       [ 7.55118635e-02],
       [ 4.88802931e-01],
       [ 1.97375475e+00],
       [-2.28660049e+00],
       [ 2.71381922e-01],
       [ 1.68654118e+00],
       [ 5.58571583e-01],
       [ 5.91578013e-01],
       [ 1.01772789e+00],
       [ 2.07766393e+00],
       [ 8.92087933e-01],
       [ 7.54659805e-01],
       [ 1.48301199e+00],
       [ 1.66545818e+00],
       [-1.16827549e+00],
       [ 2.00524669e+00],
       [ 7.30851891e-01],
       [ 4.19389105e-01],
       [ 1.24356952e+00],
       [ 2.05219474e-01],
       [ 6.89968013e-01],
       [ 8.63261929e-01],
       [-3.62489137e+00],
       [ 1.08381485e+00],
       [-5.24448322e-01],
       [ 6.41146343e-01],
       [ 8.71299476e-01],
       [-1.73492753e+00],
       [ 2.23909814e+00],
       [ 1.09219822e+00],
       [ 2.30428666e-01],
       [ 3.53780469e-02],
       [ 1.05147305e+00],
       [-2.26191523e+00],
       [-2.54616713e+00],
       [ 8.87982681e-01],
       [-1.86310965e+00],
       [ 1.07006036e+00],
       [-3.15413741e+00],
       [ 2.77961359e+00],
       [ 1.61459205e+00],
       [ 1.60232228e+00],
       [ 7.49926927e-01],
       [-1.00896667e-01],
       [-1.94827764e+00],
       [ 1.74418539e+00],
       [ 1.21594693e+00],
       [-1.60874389e+00],
       [ 6.67606808e-01],
       [ 1.66531206e-01],
       [ 1.29307969e+00],
       [-2.47467312e+00],
       [-2.34908326e+00],
       [ 1.23264329e+00],
       [ 1.07346025e+00],
       [ 1.95730253e+00],
       [-3.48855171e+00],
       [ 2.22090252e+00],
       [ 3.36126809e-01],
       [ 2.03326031e+00],
       [ 2.24237472e+00],
       [ 1.69901547e-01],
       [ 1.25540485e+00],
       [-9.49386269e-02],
       [ 1.49543487e+00],
       [ 1.03449285e+00],
       [ 8.43901564e-01],
       [ 1.07868882e+00],
       [-2.09416098e+00],
       [ 1.68499837e+00],
       [-2.88128725e+00],
       [-4.96061280e-01],
       [ 2.85434285e-01],
       [ 2.41050040e+00],
       [ 2.32060813e+00],
       [ 2.10792788e+00],
       [-6.37390402e-01],
       [ 1.00068107e-01],
       [ 5.78891959e-01],
       [ 1.30933444e+00],
       [ 5.01193558e-01],
       [ 2.42688989e+00],
       [ 1.54140821e+00],
       [ 2.12391719e+00],
       [ 1.22866140e+00],
       [ 2.58279820e+00],
       [ 1.51911272e+00],
       [ 4.20076965e-01],
       [ 2.40347377e+00],
       [ 3.02374605e-01],
       [ 7.34991429e-01],
       [ 2.62981835e+00],
       [ 2.19975096e+00],
       [ 1.13854154e+00],
       [ 6.75965250e-01],
       [ 1.42088548e-01],
       [ 1.87467448e+00],
       [-3.07004645e+00],
       [-3.49292320e+00],
       [-3.82962977e+00],
       [-2.88735671e+00],
       [-9.76644123e-01],
       [-5.15869286e+00],
       [ 3.13805350e+00]])

In [43]:
lda.explained_variance_ratio_

array([1.])

## Saving the variables (attributes)

In [44]:
arq1 = open('target.pkl', 'wb')

In [45]:
pickle.dump(target, arq1)

In [46]:
arq1.close()

In [47]:
arq1 = open('target.pkl', 'rb')

In [48]:
target = pickle.load(arq1)

In [49]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [50]:
arq2 = open('predictor.pkl', 'wb')
pickle.dump(predictor, arq2)
arq3 = open('predictor_scaled.pkl', 'wb')
pickle.dump(predictor_scaled, arq3)
arq4 = open('predictor_le.pkl', 'wb')
pickle.dump(predictor_le, arq4)
arq5 = open('predictor_ohe.pkl', 'wb')
pickle.dump(predictor_ohe, arq5)
arq6 = open('predictor_ohe_scaled.pkl', 'wb')
pickle.dump(predictor_ohe_scaled, arq6)

# TRAINING AND TEST SET

Parameters for train_test_split:



* arrays: Names of predictor and target attributes.
* test_size: Size in percentage of test data. Default is none.
* train_size: Size in percentage of training data. Default is none.
* random_state: Naming a random state.
* shuffle: Random data shuffling. When associated with random_state, the same shuffling occurs every time. Default is True.
* stratify: Possibility of stratified data splitting. Default is None (in this case, the proportion is maintained, i.e., if there are 30% zeros and 70% ones in the dataframe, the split into training and testing will maintain this ratio).

## Import

In [51]:
from sklearn.model_selection import train_test_split

## Training and Test Set

In [105]:
x_train, x_test, y_train, y_test = train_test_split(predictor_scaled, target, test_size = 0.3, random_state = 0)

In [106]:
x_train.shape

(398, 19)

In [107]:
x_test.shape

(171, 19)

In [108]:
y_train.shape

(398,)

In [109]:
y_test.shape

(171,)

# Testing Classification Algorithms

Test using all predictors:



1.   predictor
2.   predictor_scaled
3.   predictor_le
4.   predictor_ohe
5.   predictor_ohe_scaled

## General Imports

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import pandas as pd

## **NAIVE BAYES**

https://scikit-learn.org/stable/modules/naive_bayes.html

### Imports

In [ ]:
from sklearn.naive_bayes import GaussianNB

### Naive Bayes (GaussianNB)

Training the algorithm

In [ ]:
naive = GaussianNB()
naive.fit(x_train, y_train)

Algorithm evaluation

In [ ]:
predictor_naive = naive.predict(x_test)
predictor_naive

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_naive) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_naive)

In [ ]:
print(classification_report(y_test, predictor_naive))

Analysis of training data

In [ ]:
predictor_naive_train = naive.predict(x_train)
predictor_naive_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_naive_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_naive_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = GaussianNB()
result = cross_val_score(model, predictor, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['91.81%', '91.23%', '100.00%', '100.00%', '100.00%'],
      'Test Hits': ['157', '156', '171', '171', '171'],
      'Train': ['95.23%', '94.47%', '100.00%', '100.00%', '100.00%'],
      'Train Hits': ['379', '376', '398', '398', '398'],
      'Cross-Validation': ['94.17%', '93.65%', '100.00%', '100.00%', '100.00%']}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## **SUPPORT VECTOR MACHINES (SVM)**

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

### Imports

In [ ]:
from sklearn.svm import SVC

### Support Vector Machines (SVC)

Training the algorithm

In [ ]:
svm = SVC(kernel='rbf', random_state=1, C = 6)
svm.fit(x_train, y_train)

Algorithm evaluation

In [ ]:
predictor_svm = svm.predict(x_test)
predictor_svm

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_svm) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_svm)

In [ ]:
print(classification_report(y_test, predictor_svm))

Analysis of training data

In [ ]:
predictor_svm_train = svm.predict(x_train)
predictor_svm_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_svm_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_svm_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = SVC(kernel='rbf', random_state=1, C = 6)
result = cross_val_score(model, predictor_ohe, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['91.23%', '91.23%', '91.23%', '91.23%', '100.00%'],
      'Test Hits': ['156', '156', '156', '156', '171'],
      'Train': ['88.94%', '88.94%', '88.69%', '88.94%', '100.00%'],
      'Train Hits': ['354', '354', '353', '354', '398'],
      'Cross-Validation': ['89.81%', '97.00%', '90.13%', '90.13%', '100.00%'],
      'Parameters': ["SVC(kernel='rbf', random_state=1, C = 6)", "SVC(kernel='rbf', random_state=1, C = 6)", "SVC(kernel='rbf', random_state=1, C = 6)", "SVC(kernel='rbf', random_state=1, C = 6)", "SVC(kernel='rbf', random_state=1, C = 6)"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## **LOGISTIC REGRESSION**

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

### Imports

In [110]:
from sklearn.linear_model import LogisticRegression

### Logistic Regression (LogisticRegression)

Training the algorithm

In [126]:
logistic = LogisticRegression(random_state=1, max_iter=200, penalty="l2", tol=0.0001, C=1,solver="liblinear")
logistic.fit(x_train, y_train)

LogisticRegression(C=1, max_iter=200, random_state=1, solver='liblinear')

In [127]:
logistic.intercept_

array([0.61871796])

In [128]:
logistic.coef_

array([[-0.31463636, -0.70975838, -0.28251769, -0.52638443, -0.6253388 ,
         0.85229004, -0.67294664, -0.83759662, -0.24088507,  0.30063193,
        -0.09189527, -0.10011361, -1.6068491 , -0.69725693, -1.3756038 ,
        -0.47321571, -0.04411059, -1.1147759 , -0.54972708]])

Algorithm evaluation

In [129]:
predictor_logistic = logistic.predict(x_test)
predictor_logistic

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [130]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [131]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_logistic) * 100.0))

Test Accuracy: 97.66%

In [132]:
confusion_matrix(y_test, predictor_logistic)

array([[ 60,   3],
       [  1, 107]])

In [133]:
print(classification_report(y_test, predictor_logistic))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97        63
           1       0.97      0.99      0.98       108

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

Analysis of training data

In [134]:
predictor_logistic_train = logistic.predict(x_train)
predictor_logistic_train

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1])

In [135]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_logistic_train) * 100.0))

Train Accuracy: 97.74%

In [136]:
confusion_matrix(y_train, predictor_logistic_train)

array([[143,   6],
       [  3, 246]])

#### Cross-Validation

In [137]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [138]:
model = LogisticRegression(random_state=1, max_iter=200, penalty="l2", tol=0.0001, C=1,solver="liblinear")
result = cross_val_score(model, predictor_scaled, target, cv = kfold)
result

array([1.        , 0.94736842, 1.        , 0.94736842, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.89473684,
       0.94736842, 0.94736842, 0.94736842, 1.        , 1.        ,
       0.89473684, 0.89473684, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.94736842, 0.88888889])

In [139]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

Average Accuracy: 97.52%

#### Accuracy predictors

In [140]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['97.66%', '97.66%', '99.42%', '100.00%', '100.00%'],
      'Test Hits': ['167', '167', '170', '171', '171'],
      'Train': ['95.98%', '97.74%', '99.75%', '100.00%', '100.00%'],
      'Train Hits': ['382', '389', '397', '398', '398'],
      'Cross-Validation': ['95.07%', '97.52%', '99.47%', '99.82%', '100.00%'],
      'Parameters': ["LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')",
                     "LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')",
                     "LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')",
                     "LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')",
                     "LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

,Predictor,Test,Test Hits,Train,Train Hits,Cross-Validation,Parameters
0,predictor,97.66%,167,95.98%,382,95.07%,"LogisticRegression(random_state=1, max_iter=20..."
1,predictor_scaled,97.66%,167,97.74%,389,97.52%,"LogisticRegression(random_state=1, max_iter=20..."
2,predictor_le,99.42%,170,99.75%,397,99.47%,"LogisticRegression(random_state=1, max_iter=20..."
3,predictor_ohe,100.00%,171,100.00%,398,99.82%,"LogisticRegression(random_state=1, max_iter=20..."
4,predictor_ohe_scaled,100.00%,171,100.00%,398,100.00%,"LogisticRegression(random_state=1, max_iter=20..."

## **KNN**

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

### Imports

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

### INSTANCE-BASED LEARNING KNN (KNeighborsClassifier)

Training the algorithm

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)
knn.fit(x_train, y_train)

Algorithm evaluation

In [ ]:
predictor_knn = knn.predict(x_test)
predictor_knn

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_knn) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_knn)

In [ ]:
print(classification_report(y_test, predictor_knn))

Analysis of training data

In [ ]:
predictor_knn_train = knn.predict(x_train)
predictor_knn_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_knn_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_knn_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)
result = cross_val_score(model, predictor_scaled, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:

# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['94.74%', '95.91%', '94.74%', '95.32%', '100.00%'],
      'Test Hits': ['162', '164', '162', '163', '171'],
      'Train': ['95.48%', '96.98%', '95.73%', '96.23%', '99.75%'],
      'Train Hits': ['380', '386', '381', '383', '397'],
      'Cross-Validation': ['93,65%', '96.47%', '94.02%', '94.54%', '99.82%'],
      'Parameters': ["KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)",
                     "KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)",
                     "KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)",
                     "KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)",
                     "KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## **DECISION TREE**

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

### Imports

In [ ]:
from sklearn.tree import DecisionTreeClassifier

### Decision Tree (DecisionTreeClassifier)

Training the algorithm

In [ ]:
tree = DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)
tree.fit(x_train, y_train)

Algorithm evaluation

In [ ]:
predictor_tree = tree.predict(x_test)
predictor_tree

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_tree) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_tree)

In [ ]:
print(classification_report(y_test, predictor_tree))

Analysis of training data

In [ ]:
predictor_tree_train = tree.predict(x_train)
predictor_tree_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_tree_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_tree_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 2)

In [ ]:
model = DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)
result = cross_val_score(model, predictor, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['95.91%', '95.91%', '100.00%', '100.00%', '100.00%'],
      'Test Hits': ['164', '164', '171', '171', '171'],
      'Train': ['98.74%', '98.74%', '100.00%', '100.00%', '100.00%'],
      'Train Hits': ['393', '393', '398', '398', '398'],
      'Cross-Validation': ['94.04%', '94.04%', '100.00%', '100.00%', '100.00%'],
      'Parameters': ["DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)",
                     "DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)",
                     "DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)",
                     "DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)",
                     "DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## **RANDOM FOREST**

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

### Imports

In [ ]:
from sklearn.ensemble import RandomForestClassifier

### Random Forest (RandomForestClassifier)

Training the algorithm

In [ ]:
random = RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)
random.fit(x_train, y_train)

Algorithm evaluation

In [ ]:
predictor_random = random.predict(x_test)
predictor_random

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_random) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_random)

In [ ]:
print(classification_report(y_test, predictor_random))

Analysis of training data

In [ ]:
predictor_random_train = random.predict(x_train)
predictor_random_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_random_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_random_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)
result = cross_val_score(model, predictor, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['96.49%', '96.49%', '100.00%', '100.00%', '100.00%'],
      'Test Hits': ['165', '165', '171', '171', '171'],
      'Train': ['97.74%', '97.74%', '99.50%', '100.00%', '100.00%'],
      'Train Hits': ['389', '389', '396', '398', '398'],
      'Cross-Validation': ['95.41%', '95.41%', '99.30%', '100.00%', '100.00%'],
      'Parameters': ["RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)",
                     "RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)",
                     "RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)",
                     "RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)",
                     "RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## XGBOOST

https://xgboost.readthedocs.io/en/latest/

### Imports

In [144]:
from xgboost import XGBClassifier

### XGBOOST (XGBClassifier)

Training the algorithm

In [362]:
xg = XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)
xg.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.075, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=35, ...)

Algorithm evaluation

In [363]:
predictor_xg = xg.predict(x_test)
predictor_xg

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [364]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [365]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_xg) * 100.0))

Test Accuracy: 98.25%

In [366]:
confusion_matrix(y_test, predictor_xg)

array([[ 62,   1],
       [  2, 106]])

In [367]:
print(classification_report(y_test, predictor_xg))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98        63
           1       0.99      0.98      0.99       108

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

Analysis of training data

In [368]:
predictor_xg_train = xg.predict(x_train)
predictor_xg_train

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1])

In [369]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_xg_train) * 100.0))

Train Accuracy: 99.25%

In [370]:
confusion_matrix(y_train, predictor_xg_train)

array([[146,   3],
       [  0, 249]])

#### Cross-Validation

In [371]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [372]:
model = XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)
result = cross_val_score(model, predictor, target, cv = kfold)
result

array([1.        , 0.94736842, 1.        , 0.94736842, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.94736842, 1.        , 0.94736842,
       0.89473684, 0.94736842, 0.94736842, 1.        , 1.        ,
       1.        , 0.84210526, 0.94736842, 1.        , 1.        ,
       1.        , 1.        , 0.94736842, 0.84210526, 0.83333333])

In [373]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

Average Accuracy: 96.64%

#### Accuracy predictors

In [374]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['98.25%', '98.25%', '100.00%', '100.00%', '100.00%'],
      'Test Hits': ['168', '168', '171', '171', '171'],
      'Train': ['99.25%', '99.25%', '100.00%', '100.00%', '100.00%'],
      'Train Hits': ['395', '395', '398', '398', '398'],
      'Cross-Validation': ['96.64%', '96.64%', '100.00%', '100.00%', '100.00%'],
      'Parameters': ["XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)",
                     "XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)",
                     "XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)",
                     "XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)",
                     "XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)"
                    ]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

,Predictor,Test,Test Hits,Train,Train Hits,Cross-Validation,Parameters
0,predictor,98.25%,168,99.25%,395,96.64%,"XGBClassifier(max_depth=2, learning_rate=0.075..."
1,predictor_scaled,98.25%,168,99.25%,395,96.64%,"XGBClassifier(max_depth=2, learning_rate=0.075..."
2,predictor_le,100.00%,171,100.00%,398,100.00%,"XGBClassifier(max_depth=2, learning_rate=0.075..."
3,predictor_ohe,100.00%,171,100.00%,398,100.00%,"XGBClassifier(max_depth=2, learning_rate=0.075..."
4,predictor_ohe_scaled,100.00%,171,100.00%,398,100.00%,"XGBClassifier(max_depth=2, learning_rate=0.075..."

## **LIGHTGBM**

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html

Installing LightGBM

In [ ]:
!pip install lightgbm

### Imports

In [ ]:
import lightgbm as lgb
from datetime import datetime

### LIGHTGBM (lightgbm)

Preparation to test & train

In [ ]:
dataset = lgb.Dataset(x_train,label=y_train)

**Hyperparameters**

**Adjustment Control**

num_leaves: defines the number of leaves to be formed in a tree. There is no direct relationship between num_leaves and max_depth, and therefore, the two should not be linked to each other.

max_depth: specifies the maximum depth or level to which the tree can grow.

**Speed Control**

learning_rate: learning rate determines the impact of each tree on the final result.

max_bin: A smaller value for max_bin greatly reduces processing time by discretizing feature values into discrete bins, which is computationally cheaper.

**Precision Control**

num_leaves: a high value produces deeper trees with higher precision but leads to overfitting.

max_bin: high values have a similar effect to increasing the value of num_leaves and also slow down the training process.

In [ ]:
parameters = {'num_leaves':250,
              'objective':'binary',
              'max_depth':2,
              'learning_rate':.05,
              'max_bin':100}

Training the algorithm

In [ ]:
lgbm=lgb.train(parameters,dataset,num_boost_round=200)

In [ ]:
start = datetime.now()
lgbm = lgb.train(parameters, dataset)
end = datetime.now()

elapsed_time = end - start
elapsed_time

Algorithm evaluation

In [ ]:
predictor_lgbm = lgbm.predict(x_test)
predictor_lgbm

In [ ]:
predictor_lgbm.shape

In [ ]:
for i in range(0, 171):
    if predictor_lgbm[i] >= .5:
       predictor_lgbm[i] = 1
    else:
       predictor_lgbm[i] = 0

In [ ]:
predictor_lgbm

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_lgbm) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_lgbm)

In [ ]:
print(classification_report(y_test, predictor_lgbm))

Analysis of training data

In [ ]:
predictor_lgbm_train = lgbm.predict(x_train)
predictor_lgbm_train

In [ ]:
predictor_lgbm_train.shape

In [ ]:
for i in range(0, 398):
    if predictor_lgbm_train[i] >= .5:
       predictor_lgbm_train[i] = 1
    else:
       predictor_lgbm_train[i] = 0

In [ ]:
predictor_lgbm_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_lgbm_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_lgbm_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = lgb.LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)
result = cross_val_score(model, predictor_ohe_scaled, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor', 'predictor_scaled', 'predictor_le', 'predictor_ohe', 'predictor_ohe_scaled'],
      'Test': ['97.66%', '97.08%', '100.00%', '100.00%', '100.00%'],
      'Test Hits': ['167', '166', '171', '171', '171'],
      'Train': ['98.74%', '98.74%', '100.00%', '100.00%', '100.00%'],
      'Train Hits': ['393', '393', '398', '398', '398'],
      'Cross-Validation': ['96.11%', '96.11%', '100.00%', '100.00%', '100.00%'],
      'Parameters': ["LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)",
                     "LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)",
                     "LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)",
                     "LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)",
                     "LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## **CATBOOST**

https://catboost.ai/en/docs/

Installing CatBoost

In [ ]:
!pip install catboost

### Imports

In [ ]:
from catboost import CatBoostClassifier

### CATBOOST (CatBoostClassifier)

Preparation to test & train

In [ ]:
df

In [ ]:
predictor_catboost = df.iloc[:,1:20]

In [ ]:
predictor_catboost.head()

In [ ]:
target_catboost = df.iloc[:, 0]

In [ ]:
target_catboost

Training and test set

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(predictor_catboost, target_catboost, test_size = 0.3, random_state = 0)

In [ ]:
catboost = CatBoostClassifier(task_type='CPU', iterations=150, learning_rate=0.05, depth = 8, random_state = 5, eval_metric='Accuracy')

In [ ]:
catboost.fit(x_train, y_train, eval_set=(x_test, y_test))

Algorithm evaluation

In [ ]:
predictor_cat = catboost.predict(x_test)
predictor_cat

In [ ]:
y_test

In [ ]:
print("Test Accuracy: %.2f%%" % (accuracy_score(y_test, predictor_cat) * 100.0))

In [ ]:
confusion_matrix(y_test, predictor_cat)

In [ ]:
print(classification_report(y_test, predictor_cat))

Analysis of training data

In [ ]:
predictor_cat_train = catboost.predict(x_train)
predictor_cat_train

In [ ]:
print("Train Accuracy: %.2f%%" % (accuracy_score(y_train, predictor_cat_train) * 100.0))

In [ ]:
confusion_matrix(y_train, predictor_cat_train)

#### Cross-Validation

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
model = CatBoostClassifier(task_type='CPU', iterations=200, learning_rate=0.1, depth = 8, random_state = 5, eval_metric='Accuracy')
result = cross_val_score(model, predictor, target, cv = kfold)
result

In [ ]:
print("Average Accuracy: %.2f%%" % (result.mean() * 100.0))

#### Accuracy predictors

In [ ]:
# Sample data
ap = {'Predictor': ['predictor_cat'],
      'Test': ['96.49%'],
      'Test Hits': ['165'],
      'Train': ['98.49%'],
      'Train Hits': ['392'],
      'Cross-Validation': ['96.64%'],
      'Parameters': ["CatBoostClassifier(task_type='CPU', iterations=200, learning_rate=0.1, depth = 8, random_state = 5, eval_metric='Accuracy')"]}

# Creating a DataFrame
ap_df = pd.DataFrame(ap)

# Displaying the table
ap_df

## *ALGORITHMS RESULTS*

# Sample data

Naive Bayes (GaussianNB):

Support Vector Machines (SVC):

Logistic Regression (LogisticRegression):

INSTANCE-BASED LEARNING KNN (KNeighborsClassifier):

Decision Tree (DecisionTreeClassifier):

Random Forest (RandomForestClassifier):

XGBOOST (XGBClassifier):

LIGHTGBM (lightgbm):

CATBOOST (CatBoostClassifier):

In [141]:
ar = {'Algorithms': ['Naive Bayes (GaussianNB)',
                     'Support Vector Machines (SVC)',
                     'Logistic Regression (LogisticRegression)',
                     'INSTANCE-BASED LEARNING KNN',
                     'Decision Tree (DecisionTreeClassifier)',
                     'Random Forest (RandomForestClassifier)',
                     'XGBOOST (XGBClassifier)',
                     'LIGHTGBM (lightgbm)',
                     'CATBOOST'
                     ],
      'Predictor': ['predictor', 'predictor_ohe', 'predictor_scaled', 'predictor_scaled', 'predictor', 'predictor', 'predictor', 'predictor', 'predictor_cat'],
      'Test': ['91.81%', '91.23%', '97.66%', '95.91%', '95.91%', '96.49%', '98.25%', '97.66%', '96.49%'],
      'Test Hits': ['157', '156', '167', '164', '164', '165', '168', '167', '165'],
      'Train': ['95.23%', '88.94%', '97.74%', '96.98%', '98.74%', '97.74%', '99.25%', '98.74%', '98.49%'],
      'Train Hits': ['379', '354', '389', '386', '393', '389', '395', '393', '392'],
      'Cross-Validation': ['94.17%', '90.13%', '97.52%', '96.47%', '94.04%', '95.41%', '96.64%', '96.11%', '96.64%'],
      'Parameters': ['',
                     "SVC(kernel='rbf', random_state=1, C = 6)",
                     "LogisticRegression(random_state=1, max_iter=200, penalty='l2', tol=0.0001, C=1,solver='liblinear')",
                     "KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=1)",
                     "DecisionTreeClassifier(criterion='gini', random_state=0, max_depth=5)",
                     "RandomForestClassifier(n_estimators = 500, criterion = 'gini', random_state=0, max_depth=3)",
                     "XGBClassifier(max_depth=2, learning_rate=0.075, n_estimators=100, objective='binary:logistic', random_state=3)",
                     "LGBMClassifier(num_leaves = 250, objective = 'binary', max_depth = 2, learning_rate = .05, max_bin =100)",
                     "CatBoostClassifier(task_type='CPU', iterations=200, learning_rate=0.1, depth = 8, random_state = 5, eval_metric='Accuracy')"
                    ]}

# Creating a DataFrame
ar_df = pd.DataFrame(ar)

# Sorting by the 'Test' column in descending order
ar_df_sorted = ar_df.sort_values(by=['Test', 'Train', 'Cross-Validation'], ascending=False)

# Displaying the sorted table
ar_df_sorted

,Algorithms,Predictor,Test,Test Hits,Train,Train Hits,Cross-Validation,Parameters
6,XGBOOST (XGBClassifier),predictor,98.25%,168,99.25%,395,96.64%,"XGBClassifier(max_depth=2, learning_rate=0.075..."
7,LIGHTGBM (lightgbm),predictor,97.66%,167,98.74%,393,96.11%,"LGBMClassifier(num_leaves = 250, objective = '..."
2,Logistic Regression (LogisticRegression),predictor_scaled,97.66%,167,97.74%,389,97.52%,"LogisticRegression(random_state=1, max_iter=20..."
8,CATBOOST,predictor_cat,96.49%,165,98.49%,392,96.64%,"CatBoostClassifier(task_type='CPU', iterations..."
5,Random Forest (RandomForestClassifier),predictor,96.49%,165,97.74%,389,95.41%,"RandomForestClassifier(n_estimators = 500, cri..."
4,Decision Tree (DecisionTreeClassifier),predictor,95.91%,164,98.74%,393,94.04%,"DecisionTreeClassifier(criterion='gini', rando..."
3,INSTANCE-BASED LEARNING KNN,predictor_scaled,95.91%,164,96.98%,386,96.47%,"KNeighborsClassifier(n_neighbors=5, metric='mi..."
0,Naive Bayes (GaussianNB),predictor,91.81%,157,95.23%,379,94.17%,
1,Support Vector Machines (SVC),predictor_ohe,91.23%,156,88.94%,354,90.13%,"SVC(kernel='rbf', random_state=1, C = 6)"

# **SAVING DATA FOR DEPLOYMENT**

## Imports

In [378]:
import numpy as np

## Saving Data for Deployment

In [379]:
predictor

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 6.656e-01, 2.654e-01,
        4.601e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.866e-01, 1.860e-01,
        2.750e-01],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 4.245e-01, 2.430e-01,
        3.613e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 3.094e-01, 1.418e-01,
        2.218e-01],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 8.681e-01, 2.650e-01,
        4.087e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 6.444e-02, 0.000e+00,
        2.871e-01]])

In [380]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [381]:
np.savetxt('predictor.csv', predictor, delimiter=',')

In [382]:
np.savetxt('target.csv', target, delimiter=',')

# **INTRODUCTION TO HYPERPARAMETER OPTIMIZATION**

## **GRID SEARCH**

### Imports

In [383]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier

## **Grid Search (Gradient Boosting Classifier)**

In [384]:
# Creating the algorithm
gbm = GradientBoostingClassifier(random_state=0)

In [386]:
# Defining the hyperparameter space
param_grid = dict(
    n_estimators=[20, 50, 100, 250],
    learning_rate=[0.05, 0.1, 0.5],
    max_depth=[1, 2, 3, 4, 5],
)

In [387]:
print('Number of Hyperparameter Combinations: ',
      len(param_grid['n_estimators']) * len(param_grid['learning_rate']) * len(param_grid['max_depth']))

Number of Hyperparameter Combinations:  60

In [388]:
# Configuring the search with Grid search
grid_search = GridSearchCV(gbm, param_grid, scoring='roc_auc', cv=4)

In [389]:
# Configuring the best hyperparameters
grid_search.fit(x_train, y_train)

GridSearchCV(cv=4, estimator=GradientBoostingClassifier(random_state=0),
             param_grid={'learning_rate': [0.05, 0.1, 0.5],
                         'max_depth': [1, 2, 3, 4, 5],
                         'n_estimators': [20, 50, 100, 250]},
             scoring='roc_auc')

In [390]:
# Best Hyperparameters
best_hyperparameters = grid_search.best_params_
print("Best Hyperparameters:", best_hyperparameters)

Best Hyperparameters: {'learning_rate': 0.5, 'max_depth': 2, 'n_estimators': 250}

In [391]:
# Data relationship for all models
result_df = pd.DataFrame(grid_search.cv_results_)
print(result_df.shape)
result_df.head(3)

(60, 15)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,mean_test_score,std_test_score,rank_test_score
0,0.046992,0.006403,0.003609,0.000308,0.05,1,20,"{'learning_rate': 0.05, 'max_depth': 1, 'n_est...",0.959245,0.976019,0.957062,0.957934,0.962565,0.007806,51
1,0.105651,0.008610,0.003502,0.000238,0.05,1,50,"{'learning_rate': 0.05, 'max_depth': 1, 'n_est...",0.962033,0.971350,0.976896,0.984307,0.973647,0.008129,43
2,0.201290,0.013108,0.004201,0.000825,0.05,1,100,"{'learning_rate': 0.05, 'max_depth': 1, 'n_est...",0.984127,0.968591,0.983653,0.988666,0.981259,0.007571,33

In [392]:
# Sorting the best results
result_df.sort_values(by='mean_test_score', ascending=False, inplace=True)

result_df.reset_index(drop=True, inplace=True)

result_df[['param_max_depth', 'param_learning_rate', 'param_n_estimators',
            'mean_test_score', 'std_test_score']].head()

,param_max_depth,param_learning_rate,param_n_estimators,mean_test_score,std_test_score
0,2,0.5,250,0.988564,0.010438
1,1,0.5,250,0.987971,0.006653
2,2,0.5,50,0.987872,0.010970
3,2,0.5,100,0.987832,0.012717
4,3,0.5,250,0.987300,0.012970